- apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
- libs/components/affine-editor/src/Editor.tsx
In the original solution, after a new page is created, the new editor constructor cannot notify the parent component via ref, resulting in the parent component not being able to update the scrollContainer of the scrollManager
> fix: scrollManager can not get scrollcontainer after create new page

- libs/components/editor-core/src/RenderRoot.tsx
- libs/components/editor-core/src/Selection.tsx
track pad double finger scroll could active selection block
> feat: fix-track-pad-scroll

- libs/components/common/src/lib/text/slate-utils.ts
Due to https://github.com/toeverything/AFFiNE/pull/198
```ts
// start
{
"text": {
"value": [
{
"text": "1111222"
}
]
}
}
// after enter
{
"text": {
"value": [
{
"text": "1111"
}
]
}
},
{
"text": {
"value": [
{
"text": "222"
}
]
}
}
// after backspace
{
"text": {
"value": [
{
"text": "1111"
},
{
"text": "222"
},
]
}
}
// after enter again
{
"text": {
"value": [
{
"text": "1111"
}
]
}
},
{
"text": {
"value": [
{
"text": ""  // <-- a empty text
},
{
"text": "222"
},
]
}
}
```
https://user-images.githubusercontent.com/18554747/184800616-4fab1ab7-1065-40ab-bf5f-bb10605d0379.mov
> fix: filter empty string when getContentBetween

- libs/datasource/db-service/src/services/editor-block/templates/template-factory.ts
user can quick create get-started page by template.
> feat: add get-started template

- libs/components/ui/src/select/Select.tsx
When selecting a language in the code block, using arrow keys, enter selects the language but gets the drop down stuck in an open state, no clicking elsewhere can close it, you must pick another (or the same) option
Fixed by explicitly controlling the open state, though left it open for override if need be by putting it before the spread props.
BEFORE:
https://www.loom.com/share/8d1e360e18034468817be165bdb698e2
AFTER:
https://www.loom.com/share/34dd8bb52e7146d780e02a383da5919f
> fix(component): make Select close when option chosen with Enter key

- libs/components/editor-plugins/src/menu/inline-menu/config.ts
- libs/components/editor-plugins/src/menu/inline-menu/menu-item/DropdownItem.tsx
- libs/components/editor-plugins/src/menu/inline-menu/menu-item/IconItem.tsx
Modified the code used for assigning shortcuts based on the OS.
Feat : Split 'inlineMenuShortcuts' to 'WinInlineMenuShortcuts' and 'MacInlineMenuShortcuts' functions
**_Fix #346_**
> Fix: Added seperate shortcut keys for Windows and Mac.

- libs/components/editor-blocks/src/blocks/group/scene-kanban/RefPage.tsx
Active the first block after opening the ref page
> fix: empty ref page

- apps/ligo-virgo/webpack.config.js
Please ensure the environment variable exists `AFFINE_FEATURE_FLAG_TOKEN` before merging.
> fix: add feature flag token to env

- apps/venus/src/app/common/Header.tsx
- apps/venus/src/app/common/MobileHeader.tsx
- libs/components/layout/src/settings-sidebar/Settings/SettingsList.tsx
- Fix empty language select at first time
- the `i18n.language` return `"en-US"`, but we only have `"en"` option
- Add mobile multiple languages support
`i18n.language` is set to the current detected or set language.
> ## resolvedLanguage
> i18next.resolvedLanguage
> Is set to the current resolved language.
> It can be used as primary used language, for example in a language switcher.
see https://www.i18next.com/overview/api#resolvedlanguage
> fix: default language

- libs/components/common/src/lib/text/EditableText.tsx
Fixes issue #336.
TL;DR: Previously when using markdown, after hitting space and having your markdown processed, the text editor would move the cursor all the way to start. This PR keeps it at the end of the last thing processed.
https://user-images.githubusercontent.com/32908859/192921998-a549a1e8-cb39-4a07-814d-5e66c1600aa0.mov
https://user-images.githubusercontent.com/32908859/192921636-c3d12b80-6a48-4f8d-8d0b-60aeaee8d67f.mov
> Fix: Move cursor to end of markdown

- libs/components/editor-blocks/src/blocks/text/TextView.tsx
> fix: once block type changed, the TextBlock node should be re-render

- packages/app/src/pages/workspace/[workspaceId]/[pageId].tsx
When the screen width is 1050px, there is no spacing between the editor and the sidebar and it looks a bit awkward.
This pr add padding.
> feat: add padding for editor

- package.json
- packages/data-center/package.json
- pnpm-lock.yaml
@blocksuite/editor is not needed in data-center, I removed the dependency and changed update BlockSuite script accordingly
> fix: remove redundant package in data-center

- packages/data-center/package.json
- packages/data-center/src/provider/affine/apis/__tests__/token.spec.ts
- packages/data-center/src/provider/affine/apis/token.ts
- pnpm-lock.yaml
should fix https://github.com/toeverything/AFFiNE/issues/901
The original parsing logic for base64 -> `utf-8` string may not parse some tokens correctly. We would better use a 3rd party library (js-base64, suggested by @DiamondThree ) instead.
> fix: token parsing

- packages/data-center/src/provider/tauri-ipc/index.ts
- packages/data-center/src/provider/tauri-ipc/utils.ts
This will cause "Failed to read blob file /t5GGutpCXHqh53U8jt1ozHAKhcf2DaQZGSGLzwp6mUU=" on the console.
> fix: client not saving avatar blob on first creating workspace

- apps/web/src/components/message-center-handler/index.tsx
tested locally by following steps:
- login app
- change `affine:token` in localstorage to an invalid one
- refresh page
- `/api/user/token` reports 400 and following load workspace calls will fail with 401
- on 401 error, the page will be redirected to the home page ('/')
this and https://github.com/toeverything/AFFiNE/pull/770 should fix https://github.com/toeverything/AFFiNE/issues/932
> fix: on token invalidation it shall be redirected to home page

- .github/workflows/languages-sync.yml
- packages/i18n/src/index.ts
Steps to reproduce:
1. switch to "简体中文"
2. fefresh page
expect: "简体中文"
received: 'en'
> fix: `zh-Hans` i18n fails on page reload

- packages/component/src/styles/theme.ts
Preview:
When there is a submenu, the old hovering color was considered too bright in dark theme. This PR can mitigate this issue by changing to a color with less brightness.
> fix: submenu dark theme hover background theming

- packages/component/src/stories/BlockSuiteEditor.stories.tsx
Fix a typo in the `BlockSuiteEditor.stories.tsx` file.
> chore: typo fix

- apps/web/package.json
- packages/component/package.json
- packages/data-center/package.json
- packages/data-center/src/datacenter.ts
- packages/data-center/src/index.ts
- packages/data-center/src/logger.ts
- packages/data-center/src/provider/affine/affine.ts
- packages/data-center/src/provider/affine/apis/google.ts
- packages/data-center/src/provider/affine/channel.ts
- packages/data-center/src/provider/base.ts
- packages/data-center/src/provider/local/local.ts
- packages/data-center/src/provider/tauri-ipc/index.ts
- packages/data-center/src/types/index.ts
- packages/debug/README.md
- packages/debug/package.json
- packages/debug/src/index.ts
- packages/i18n/package.json
- packages/store/package.json
- packages/store/src/app/user/index.ts
- pnpm-lock.yaml
- tsconfig.json
- logger enabled by default in dev mode
- enable logger in production by adding `?debug` to the URL
Note: this logger does not filter logs. If you want to, use the default browser logging settings instead.
> feat: debug logger with levels

- apps/web/src/pages/_app.tsx
- packages/i18n/package.json
- packages/i18n/src/index.ts
- pnpm-lock.yaml
Closes: https://github.com/toeverything/AFFiNE/issues/1239
We don't use next-i18next actually, so we could remove it
> chore: remove `next-i18next`

- .github/workflows/build-test-version.yml
- .github/workflows/build.yml
- .github/workflows/changlog.yml
- .github/workflows/client-app.yml
- .github/workflows/languages-sync.yml
- .github/workflows/publish.yml
- .github/workflows/update-block-suite.yml
- package.json
Ref: https://github.com/pnpm/action-setup#version
Everyone should run `corepack prepare` && `corepack enable` locally before modifying `pnpm-lock.yaml`
> ci: setup pnpm from corepack config to avoid flaky lockfile

- .vscode/launch.json
That way, people can launch the project quicker in vscode after cloning it
> chore: add launch.json for vscode

- .github/workflows/client-app.yml
- .gitignore
- .npmrc
- apps/desktop/package.json
- apps/desktop/src-tauri/src/commands/workspace.rs
- apps/desktop/src-tauri/src/state.rs
- apps/web/src/hooks/__tests__/use-blocksuite-workspace-helper.spec.ts
- package.json
- packages/component/src/stories/BlockSuiteEditor.stories.tsx
- packages/env/src/index.ts
- packages/env/tsconfig.json
- pnpm-lock.yaml
- tsconfig.json
This PR removes the usage of cross-env in favor of the pnpm shell-emulator.
refs: vitejs/vite#10023
> chore: replace cross-env with shell-emulator & misc

- apps/web/src/components/blocksuite/header/header-right-items/EditorOptionMenu.tsx
To fix this [Could not export as markdown](https://github.com/toeverything/AFFiNE/issues/1588).
> fix: globalThis.editor undefined

- .github/workflows/client-app.yml
before: duplicate rules will trigger upload twice but will delete after uploaded the first time
after:
https://github.com/toeverything/AFFiNE/actions/runs/4459528720
https://github.com/toeverything/AFFiNE/releases/tag/untagged-ae7937bcf4e84127959d
> fix: fix windows release not found

- .github/workflows/release-desktop-app.yml
- apps/electron/forge.config.js
- apps/electron/yarn.lock
fix https://github.com/toeverything/AFFiNE/issues/1509
Successful build at https://github.com/pengx17/AFFiNE/actions/runs/4598337291
References:
- [Logseq's code signing workflow](https://github.com/logseq/logseq/actions/runs/4575859183/jobs/8079439397)
- https://www.codiga.io/blog/notarize-sign-electron-app/
- https://www.electronforge.io/guides/code-signing/code-signing-macos
Requires to set the following new secrets:
> build: MacOS code signing

- apps/electron/yarn.lock
- packages/y-indexeddb/benchmark/index.ts
- packages/y-indexeddb/package.json
- packages/y-indexeddb/src/__tests__/index.spec.ts
- packages/y-indexeddb/src/index.ts
- tests/libs/utils.ts
- tests/parallels/local-first-setting-page.spec.ts
- yarn.lock
Fixes: https://github.com/toeverything/AFFiNE/issues/1878
outputs:
```shell
create many persistence
[
PerformanceMeasure {
name: 'yjs',
entryType: 'measure',
startTime: 1138.3797089457512,
duration: 3805.7039580345154,
detail: null
},
PerformanceMeasure {
name: 'toeverything',
entryType: 'measure',
startTime: 4944.275416970253,
duration: 1129.9851250052452,
detail: null
}
]
single persistence with huge updates
[
PerformanceMeasure {
name: 'yjs',
entryType: 'measure',
startTime: 6075.344083964825,
duration: 356.324874997139,
detail: null
},
PerformanceMeasure {
name: 'toeverything',
entryType: 'measure',
startTime: 6431.707749962807,
duration: 196.39375001192093,
detail: null
}
]
```
> perf(y-indexeddb): improve boost and loading time

- apps/electron/scripts/generate-assets.mjs
fix https://github.com/toeverything/AFFiNE/issues/1960
There are two options to fix this issue:
1. just use git bash on windows https://gitforwindows.org/
2. force zx to read powershell as execute shell env
> fix: force to use powershell on windows to fix zx script crash

- apps/web/src/components/pure/workspace-slider-bar/style.ts
Using some css properties that are not very compatible may be risky.
> chore: disable slider bar link item drag

- packages/y-indexeddb/src/__tests__/index.spec.ts
- packages/y-indexeddb/src/index.ts
Related: https://github.com/toeverything/AFFiNE/issues/2084
> fix(y-indexeddb): alert user when write operation unfinished

- apps/electron/layers/main/src/data/sqlite.ts
- packages/component/src/ui/modal/styles.ts
> fix: closing modal sometimes covered by header

- apps/electron/layers/main/src/index.ts
We are relying on GPU rendering, especially on the Edgeless Mode
> fix(electron): remove disableHardwareAcceleration

- packages/theme/src/index.ts
Fixes: https://github.com/toeverything/AFFiNE/issues/2234
Fix issue #2205 
z-index of the pop-over comoponent should not be smaller than the side bar component.
> style: fix popover z-index

- apps/web/src/components/pure/quick-search-modal/index.tsx
> chore: disable navigation path

- apps/web/src/components/pure/help-island/index.tsx
- apps/web/src/components/pure/help-island/style.ts
- packages/component/src/theme/global.css
https://user-images.githubusercontent.com/102217452/236429188-862eef9b-1469-4f65-995c-70b9ec50e7ff.mov
> chore: update the style of help island in edgeless mode

- packages/component/src/ui/menu/styles.ts
> fix: vertical alignment of item on share menu

- apps/web/src/components/blocksuite/workspace-header/editor-mode-switch/index.tsx
- apps/web/src/hooks/root/use-on-transform-workspace.ts
- apps/web/src/utils/toast.ts
- packages/i18n/src/resources/en.json
- tests/parallels/change-page-mode.spec.ts
Fixes: https://github.com/toeverything/AFFiNE/issues/2289
> fix(component): toast too many times when switch page mode

- apps/server/package.json
- apps/server/scripts/gen-auth-key.ts
- apps/server/src/config/def.ts
- apps/server/src/config/default.ts
- apps/server/src/modules/auth/service.ts
- apps/server/src/tests/app.e2e.ts
- yarn.lock
BTW, we don't need an application-level salt since `@node-rs/bcrypt` will generate a random salt by `OsRng` by default while hashing.
> chore(server): remove bcrypt to avoid node-gyp usage

- packages/templates/src/AFFiNE-Docs.md
seperate -> separate
seperates -> separates
> fix: typo in AFFiNE-Docs.md

- packages/component/.storybook/preview.tsx
See also https://storybook.js.org/docs/react/essentials/backgrounds
> chore: disable confused storybook backgrounds addon

- apps/web/src/layouts/workspace-layout.tsx
- packages/workspace/src/atom.ts
Fixes: https://github.com/toeverything/AFFiNE/issues/2381
> fix: infinite reloading

- apps/web/src/components/affine/workspace-setting-detail/index.css.ts
- apps/web/src/components/affine/workspace-setting-detail/panel/general/index.tsx
- packages/i18n/src/resources/en.json
- tests/parallels/local-first-delete-workspace.spec.ts
Fixes: https://github.com/toeverything/AFFiNE/issues/2402, https://github.com/toeverything/AFFiNE/issues/2531
> fix: cannot delete last workspace

- apps/web/preset.config.mjs
- packages/env/src/config.ts
I add a new build flag to trigger all page filters. Please use this flag in your code because our filter feature is still unstable.
For example:
```ts
const NewComponent = () => {
if (config.enableAllPageFilter) {
return null; // no render
}
return <div>Feature</div>
}
```
/cc @zzj3720 @danielchim
> feat: add build flag `enableAllPageFilter`

- apps/electron/layers/main/src/db/__tests__/ensure-db.spec.ts
- apps/electron/layers/main/src/db/base-db-adapter.ts
- apps/electron/layers/main/src/db/secondary-db.ts
After moving the database, a meta change was triggered. At this time, the main database was destroyed, but the sync process of the external database was still ongoing.
> fix(electron): should not continue pull when db closed

- apps/web/next.config.mjs
- apps/web/src/bootstrap/index.ts
- packages/env/src/global.ts
- packages/workspace/src/atom.ts
When `rootWorkspacesMetadataPromiseAtom` waits for `migration-done` event, it may be already loaded.
Added another hidden flag `__migration_done__: boolean;` to global to mitigate this issue.
> fix: potential race condition on app load when migration

- packages/workspace/src/atom.ts
Workspace might not init because jotai-workspace is different from the CRUD data.
Example:
In this case, the local workspace might not init because the list API didn't create the workspace into the internal hashmap. We need to do this before the promise is resolved.
reported by @zqran
> fix: init workspace before loaded

- apps/web/src/components/affine/new-workspace-setting-detail/delete-leave-workspace/delete/index.tsx
- apps/web/src/components/pure/workspace-slider-bar/WorkspaceSelector/workspace-selector.tsx
- apps/web/src/components/root-app-sidebar/index.tsx
- packages/hooks/src/__tests__/index.spec.ts
- packages/hooks/src/use-block-suite-page-references.ts
- packages/hooks/src/use-block-suite-workspace-helper.ts
- packages/hooks/src/use-block-suite-workspace-name.ts
- packages/hooks/src/use-block-suite-workspace-page.ts
Null type should be checked and skipped in the top level. In our `web,` we check whether `workspaceId` and `pageId` are at the top level to ensure they exist. Otherwise, we jump to `404` or give a skeleton for loading.
Reduce the null type could help each component focus on it's own logic instead of `if it's null, return null` or something
> refactor(hooks): reduce null types

- .gitignore
- apps/server/src/modules/sync/events/events.gateway.ts
- apps/server/src/modules/sync/events/workspace.ts
- packages/workspace/src/affine/sync-socket-io/index.ts
There are two ways to remove an awareness client's state:
1. provider should set local awareness state to null and inform other clients in awareness update callback
2. Local awareness will periodically check, each client's states have 30 seconds' timeout time  https://github.com/yjs/y-protocols/blob/ba21a9c92990743554e47223c49513630b7eadda/awareness.js#L69C8-L69C8
This PR ensures the first method work normally
> fix: disconnect awareness properly

- apps/electron/package.json
- apps/electron/src/main/application-menu/create.ts
- apps/electron/src/main/updater/electron-updater.ts
- apps/electron/src/main/updater/index.ts
- yarn.lock
The root cause is that build layers will build main/preload etc in DEVELOPMENT mode, which will result in using default updater configs (like auto download, update on quit etc)
> fix: updater not working

- .github/workflows/nightly-build.yml
Looks like `0.0.0-20230714031808-0ca9f2c` is not a valid semversion for electron-updater.
It requires it to be something like `0.0.0-channel.build-number`. The channel in the name is crucial here. 
https://github.com/electron-userland/electron-builder/blob/84ed3ff123b5ae92cd3350d64677434f9b397b76/packages/electron-updater/src/providers/GitHubProvider.ts#L59-L94
> fix: internal build updater

- apps/server/src/modules/doc/redis-manager.ts
doc guid could be like `spafe:xxxxx`, the redis key should not be destructed directly by `str.split`
> fix(server): doc guid may contains colon mark

- apps/server/src/modules/sync/events/events.gateway.ts
Currently, a single client doesn't have to join two rooms: `awareness-${workspaceId}`, `${workspaceId}`.
> perf: remove useless room

- apps/core/src/components/pure/workspace-slider-bar/collections/add-collection-button.tsx
After creating a collection, it cannot be created again, and the click will change to modify the collection. This is not expected behavior.
> fix: unable to add a second collection

- README.md
The button was not showing correctly as there was a typo. I think this should fix the issue
> docs: fix the Linux download button on the readme page

- tests/affine-local/e2e/local-first-delete-page.spec.ts
Fixes: #3359 
Added all these Tests below mentioned : 
First and second test is done in 1 single Test
page delete -> it should be deleted
page delete -> refresh page -> it should be disappear
page delete -> create new page -> refresh page -> new page should be appear -> old page should be disappear
delete multiple pages -> create multiple pages -> refresh
> test: improve e2e coverage on page deletion

- apps/core/src/providers/modal-provider.tsx
- packages/workspace/src/providers/sqlite-providers.ts
The issue is: 
- if importing workspace at the `page detail` route, when importing the page goes in skeleton
- even if we have route as `workspace/NEW_WORKSPACE_ID/all`, it still stays at the DetailPage route
Not sure why but it seems the navigation was blocked by suspense
> fix: flaky tests

- packages/sdk/.gitignore
I don't know why these files are emitted in `src` instead of `dist`
Guessing because I use `export declare const` grammar
> chore: ignore output files

- .eslintignore
- .eslintrc.js
- tsconfig.eslint.json
seems like eslint gets stuck in parsing ts files within `apps/electron/resources/web-static` in the following line
```ts
function getSourceFileVersionAsHashFromText(host, text) {
if (text.match(sourceMapCommentRegExpDontCareLineStart)) {
```
> fix: eslint stack overflow issue

- apps/electron/src/main/main-window.ts
- apps/electron/src/main/protocol.ts
- apps/electron/src/main/utils.ts
Return `set-cookie` in `handle`'s response is not working. We need to hack here using `window.webContents.session.cookie`
> fix: cookie handling in Electron

- apps/core/src/bootstrap/plugins/setup.ts
This should be removed since nowhere using it. And I'll remove this export in blocksuite soon.
> chore: remove dependency of blocksuite/blocks/std

- apps/core/src/layouts/workspace-layout.tsx
On page navigation, the whole page may blink because the suspense wrapper is at the root level.
This moves the suspense bound to each of the content containers instead.
> fix: page blink issue on navigation

- apps/core/src/components/pure/workspace-slider-bar/components/reference-page.tsx
- packages/hooks/src/use-block-suite-page-references.ts
`useBlockSuitePageReferences` should not crash if the page is being deleted.
> fix: reference page crash for deleted items

- apps/core/src/components/blocksuite/block-suite-page-list/utils.tsx
- apps/core/src/pages/workspace/detail-page.tsx
I think the issue appeared because "mode" was coming as undefined in utils.tsx file. 
So, set a default value of 'page' if mode is undefined.  With that change I was able to see the newly created page in recent list.
The other case is, When we click on existing page, it did not appear in the recent list. So, I performed setPageMode in detail-page.tsx.
> fix: recent pages list doesn't update

- packages/workspace/src/atom.ts
This will guarantee that if AFFiNE cloud server remove some workspace, we will also not display such workspace
> fix(workspace): remove item not in the adapter

- apps/electron/dev-app-update.yml
- apps/electron/package.json
- apps/electron/resources/app-update.yml
- apps/electron/scripts/common.mjs
- apps/electron/src/main/updater/custom-github-provider.ts
- apps/electron/src/main/updater/electron-updater.ts
The custom updater provider still relies on github release page and the codes are mostly brought from the original one, with the exception is the `getLatestVersion` function.
Our own `getLatestVersion` function favours channel more strictly and will not bump channels automatically, like from canary -> beta, beta -> stable.
In the future we could add more customized logic to it (if it is really needed)
> feat: custom updater provider

- apps/electron/package.json
Because the way how [Electron packager](https://github.com/electron/electron-packager) works, only the dependencies defined in `dependencies` in `package.json` will be copied into the final package.
Removing some of the blackholes greatly reduces the number of packaged files. See the result below.
This could speed up some tasks like code signing on Windows and [the lag of updater on Mac](https://github.com/toeverything/AFFiNE/issues/3834).
Before
After
> fix: reduce the number of files being packed

- apps/electron/forge.config.js
It turns out the auto-generated hash in file names may cause them to be excluded in the final bundle.
E.g., see the following
The e2e part in ses-**e2e**4fb59.js causes it to be excluded in the final bundle.
> fix: electron white screen

- apps/core/src/components/affine/auth/after-sign-in-send-email.tsx
- apps/core/src/components/affine/auth/after-sign-up-send-email.tsx
- apps/core/src/components/affine/auth/callback-url.ts
- apps/core/src/components/affine/auth/sign-in.tsx
- apps/core/src/pages/desktop-signin.tsx
- apps/core/src/pages/open-app.tsx
- apps/core/src/router.ts
- apps/electron/src/main/deep-link.ts
- apps/electron/src/main/main-window.ts
- apps/server/src/modules/auth/resolver.ts
- apps/server/src/modules/users/resolver.ts
- packages/graphql/src/graphql/get-current-user.gql
- packages/graphql/src/graphql/index.ts
- packages/graphql/src/schema.ts
Thanks to the help of @darkskygit, it turns out that we don't need any hacks within Electron by creating a hidden window and handling login inside it. Now, we have a much easier solution:
- Instead of directly calling the signin function when signing in is initiated via Electron, we can pop up the login window in the browser and initiate signIn there.
- Once Google signin is finished, it can redirect to the open-app route, fetch the JWT token, and send it to the desktop app.
- The desktop app can then accept the token and set it to the browser window using cookie.
It seems like we don't need to change the electron origin after all. I will go back and fix email login as well later on.
> feat: support google login on desktop

- apps/core/src/components/blocksuite/block-suite-header-title/styles.css.ts
fix: #4056 
Showed a border around the page title only when title input is on focus.
> fix: show border around pagetitle when renaming

- apps/core/src/components/affine/auth/sign-in-with-password.tsx
- apps/core/src/utils/cloud-utils.tsx
- apps/electron/src/main/deep-link.ts
- apps/electron/src/main/main-window.ts
- apps/electron/src/main/protocol.ts
- apps/server/src/modules/auth/next-auth-options.ts
need to handling cookies more gracefully
- if getting back cookies from api, we will mark it cross-domain available
- if sending request, add the cookies to headers
also fix some issues related to callbackUrl. If not being explicitly set in electron, it will be something like `file://./xxxx` and the api server does not like it and throw.
> fix: cookie issues in Electron

- apps/electron/src/main/config.ts
- packages/workers/src/index.ts
maybe we need a single-source-of-truth config for these urls
> fix: api url for electron

- packages/component/src/ui/modal/modal.tsx
This fixes issue #4100 where the notification text was not able to be selected when modal was open. 
@JimmFly can you review?
> fix: notification text cannot be selected when there is a modal

- apps/core/src/components/affine/new-workspace-setting-detail/delete-leave-workspace/index.tsx
- apps/core/src/components/affine/new-workspace-setting-detail/index.tsx
- apps/core/src/components/affine/new-workspace-setting-detail/labels.tsx
- apps/core/src/components/affine/new-workspace-setting-detail/members.tsx
- apps/core/src/components/affine/new-workspace-setting-detail/profile.tsx
- apps/core/src/components/affine/new-workspace-setting-detail/publish.tsx
- apps/core/src/components/affine/new-workspace-setting-detail/types.ts
- apps/electron/src/helper/db/ensure-db.ts
- apps/electron/src/helper/db/secondary-db.ts
- apps/electron/src/helper/db/workspace-db-adapter.ts
- apps/electron/src/helper/dialog/dialog.ts
- apps/electron/src/helper/exposed.ts
- apps/electron/src/helper/main-rpc.ts
- apps/electron/src/helper/provide.ts
- apps/electron/src/helper/workspace/__tests__/handlers.spec.ts
- apps/electron/src/helper/workspace/handlers.ts
- apps/electron/src/helper/workspace/index.ts
- apps/electron/src/helper/workspace/meta.ts
- packages/component/src/components/page-list/all-page.tsx
- packages/component/src/components/page-list/view/collection-bar.tsx
- packages/component/src/components/page-list/view/collection-list.tsx
thanks to https://github.com/web-infra-dev/oxc and https://github.com/antoine-coulon/skott.
This is a one time fix for the current master branch. Later we could replace parts of import plugin with oxclint for identifying circular issues in CI.
Before:
```shell
⚠ eslint-plugin-import(no-cycle): Dependency cycle detected
╭─[apps/electron/src/helper/main-rpc.ts:6:1]
6 │
7 │ import { getExposedMeta } from './exposed';
·                                ───────────
8 │
╰────
help: These paths form a cycle:
-> ./exposed - apps/electron/src/helper/exposed.ts
-> ./db - apps/electron/src/helper/db/index.ts
-> ../main-rpc - apps/electron/src/helper/main-rpc.ts
⚠ eslint-plugin-import(no-cycle): Dependency cycle detected
╭─[apps/electron/src/helper/workspace/handlers.ts:6:1]
6 │ import { logger } from …
```
> fix: circular dependencies

- apps/core/src/pages/404.tsx
close #4201 
The back to last workspace logic in 404 page just been removed, because index page will do this more safely.
There have some others logic should be improved but not this commit:
1. no 400 exception page, all in 404
2. 404 should have search params to know what resource not found and what page from
> fix(core): back home botton has no reaction 

- packages/workspace/src/blob/cloud-blob-storage.ts
- packages/workspace/src/blob/local-static-storage.ts
after #4360, fix https://github.com/toeverything/AFFiNE/issues/4363
1. no need to add suffix for `/static/${key}`, reference:
2. use `/static` path when blob is stored in CDN
> fix: use cdn api when querying static CDN files

- apps/storybook/src/stories/core.stories.tsx
Because of dropdown menu is shown in body element not in storybook root, so the assertion should use global api.
> ci(storybook): fix import page failed problem

- apps/server/src/modules/auth/next-auth-options.ts
https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters:~:text=to%20the%20client.-,select_account,-The%20authorization%20server
I am not sure but it looks like I always got the account selection prompted every time I signin with google oauth. It may help to explicitly show account selection for some users.
> fix: add prompt select_account for google login

- apps/core/src/hooks/use-navigate-helper.ts
result of `useNavigateHelper` is being used as a dependency of some registering cmdk bindings
> fix: register command re-rendering

- apps/core/src/components/page-detail-editor.css.ts
- apps/core/src/components/page-detail-editor.tsx
Close #4461 
Temporarily, content subtract heights of the header to fix safe padding issue. There need to use flex to refactor the whole layout.
Temporarily, use editor classsname to add padding bottom back, which removed on https://github.com/toeverything/blocksuite/pull/4766
> fix(component): content should subtract height of the header

- packages/templates/v1/getting-started.json
There seems to be a missing space in getting-started template. 
BTW, it's a cool project. Thank you for maintaining this incredible project, and please keep up the great work!
> fix: spacing issue in getting-started template

- apps/storybook/src/stories/page-list.stories.tsx
fix `Invalid value used as weak map key` issue.
> fix: list page storybook not rendering issue

- apps/core/src/components/affine/new-workspace-setting-detail/publish.tsx
- Currently, while pressing the tab key the [Tooltip](https://github.com/toeverything/AFFiNE/blob/master/apps/core/src/components/affine/new-workspace-setting-detail/publish.tsx#L100) component gets triggered which puts the focus on it, and after pressing the space key it goes to its child node Switch which activates its event and still gets trigger in disable mode.
- To fix the issue we need to pass a prop onChange which on getting a trigger will not enable the switch.
Fixes: https://github.com/toeverything/AFFiNE/issues/4570
**Before**
https://github.com/toeverything/AFFiNE/assets/132813311/b7a79f96-283c-4be0-92a8-4e47baf1d2f4
**After**
https://github.com/toeverything/AFFiNE/assets/132813311/4e3365c3-a966-4fe7-9ca4-0b96e5a08523
> fix: disabled form item in the settings can still be operated via keyboard

- packages/frontend/core/src/components/pure/cmdk/data.tsx
fix #3294
The reason for the bug is that when the page itself has no title, the title cannot be displayed.
> 1. There will be no content in the search results(Please try to see if you can reproduce)
> 2. Search results document title disappears
> fix(core): retrieve missing search result titles

- packages/frontend/component/src/components/page-list/page-group.tsx
- packages/frontend/component/src/components/page-list/scoped-atoms.ts
the optimization on using lodash.isEqual on selectAtom will cause crash on production build. Still need time to investigate the root cause
> fix(core): selectAtom crash on isEqual

- packages/frontend/component/src/components/page-list/page-content-preview.tsx
- packages/frontend/core/src/hooks/use-workspace.ts
- packages/frontend/hooks/src/use-block-suite-page-preview.ts
1. Sometimes `useBlockSuiteWorkspacePage(workspace, pageId)` may return `null` when switching workspace. 
2. When deleting the last workspace, based on how jotai works the atom get dep in `useWorkspace` could rerun and throw flavour not found issue.
> fix(core): possible crash issues

- packages/frontend/core/src/components/affine/setting-modal/general-setting/billing/index.tsx
- packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/actions.tsx
- packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/modals.tsx
- packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/plan-card.tsx
- Extract **cancel** and **resume** action to handle `confirm modal` & `http request`
- Show confirm dialog after clicking cancel in **billing page**
- Change pricing plan active logic, ignore recurring
> fix(core): billing cancel confirm dialog

- packages/frontend/workspace/src/affine/gql.ts
error log:
```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'currentUser')
at l (use-subscription.ts:12:8)
at o (use-subscription.ts:39:11)
at x (user-plan-button.tsx:12:26)
at ay (react-dom.production.min.js:167:137)
at s (react-dom.production.min.js:290:337)
at i_ (react-dom.production.min.js:280:389)
at react-dom.production.min.js:280:320
at iT (react-dom.production.min.js:280:325)
at iC (react-dom.production.min.js:271:88)
at iZ (react-dom.production.min.js:268:429)
a6 @ react-dom.production.min.js:189
index.js:481 React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'currentUser')
at l (use-subscription.ts:12:8)
at o (use-subscription.ts:39:11)
at x (user-plan-button.tsx:12:26)
at ay …
```
> fix(core): currentUser undefined when all workspaces deleted

- packages/frontend/core/src/components/blocksuite/block-suite-mode-switch/index.tsx
After my test, using `⌥ + S` in macos, event.key is `ß`, event.code is `KeyS`
Using KeyboardEvent.code seems to be a better solution.
The relevant code was last changed here:
https://github.com/toeverything/AFFiNE/pull/3097/files#diff-7d9ad95b8b3e47ad3d6edd26562e2553cc03171c58ed65c4c14a38b9c41effa7R48
> fix(core): fix block suite edit mode switch shortcut

- packages/frontend/workspace/package.json
- packages/frontend/workspace/src/blob/cloud-blob-storage.ts
- packages/frontend/workspace/src/blob/sqlite-blob-storage.ts
- packages/frontend/workspace/src/blob/util.ts
- yarn.lock
SVG `blob`'s type will be missing after it is being saved into data sources because it is essentially a string. This is not an issue for image because image have headers in their binary format.
For idb we have mime table that stores the mime type info, but I think it may not be that necessary since the only counter case for storing blob is svg.
> fix(core): adapt blob in sqlite for svg type

- packages/frontend/electron/src/main/protocol.ts
It looks like the challenge was not being sent in the proxied request in electron, which is the cause of the below 
https://affine-pro.slack.com/archives/C05QRGNFWUW/p1698992455643899
> fix(electron): add search to proxied url

- packages/frontend/core/src/layouts/workspace-layout.tsx
The dragged component's content may be hidden because of scrolling + virtual rendering.
Add a workaround so that the displayed content is the content when dragging just started.
> fix(component): dragged component disappear when dragging

- packages/frontend/hooks/src/use-block-suite-page-preview.ts
- packages/frontend/hooks/src/use-block-suite-page-references.ts
status: This pr fix [#11](https://github.com/toeverything/AFFiNE/issues/4865) , would be able to improve if blocksuite was able to provide page.onSync slat https://github.com/toeverything/blocksuite/issues/5249.
> fix(hooks): missing page preview and references

- packages/backend/server/src/config/default.ts
`TypeError: Cannot set property featureFlags of #<Object> which has only a getter`
> fix(server): earlyAccessPreview env override

- packages/frontend/electron/package.json
- packages/frontend/electron/scripts/dev.ts
- packages/frontend/electron/src/main/logger.ts
- packages/frontend/electron/src/main/updater/electron-updater.ts
- yarn.lock
root cause:
- should not exit the current process when reload
- electron log should not continue logging when process is quitting (which will crash if doing so
> fix(electron): dev reload

- packages/common/infra/src/blocksuite/index.ts
since we strip `page:` in keys of workspacedoc.spaces, we should also strip the prefix in meta.pages as well.
> fix(infra): page id compat fix for page ids in workspace.meta

- .github/actions/build-rust/action.yml
If Rust build was cached by nx, only the output file will be presented. The chmod command will be failed in this case like: https://github.com/toeverything/AFFiNE/actions/runs/6874496337/job/18697360212
> ci: prevent error if rust build is cached by nx
