libs/components/editor-plugins/src/placeholder/PlaceholderPanel.tsx
libs/datasource/db-service/src/services/editor-block/templates/template-factory.ts

fix check error
```
libs/components/editor-plugins/src/placeholder/PlaceholderPanel.tsx:144:11 - error TS4104: The type 'readonly [{ readonly name: "New From Quick Start"; readonly group
```

fix: check error

---

apps/ligo-virgo/src/assets/images/logo.svg
apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
apps/ligo-virgo/src/pages/workspace/docs/components/logo/Logo.tsx
apps/ligo-virgo/src/pages/workspace/docs/components/logo/index.ts
apps/ligo-virgo/src/pages/workspace/docs/components/tabs/Tabs.tsx
apps/ligo-virgo/src/pages/workspace/docs/components/tabs/index.ts
apps/ligo-virgo/src/pages/workspace/docs/workspace-name.tsx

see [Issues#33](https://github.com/toeverything/AFFiNE/issues/33)

Opti page tree header mitsuha dev

---

libs/datasource/jwt/src/adapter/yjs/binary.ts
libs/datasource/jwt/src/adapter/yjs/block.ts
libs/datasource/jwt/src/adapter/yjs/gatekeeper.ts
libs/datasource/jwt/src/adapter/yjs/history.ts
libs/datasource/jwt/src/adapter/yjs/index.ts
libs/datasource/jwt/src/adapter/yjs/operation.ts
libs/datasource/jwt/src/block/abstract.ts
libs/datasource/jwt/src/block/base.ts
libs/datasource/jwt/src/block/indexer.ts
libs/datasource/jwt/src/index.ts
libs/datasource/jwt/src/utils/event-bus.ts

fix: variable naming

---

apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
libs/components/editor-core/src/editor/scroll/scroll.ts

fix: fixed #81

---

apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
apps/ligo-virgo/src/pages/workspace/docs/collapsible-page-tree.tsx
libs/components/common/src/lib/collapsible-title/index.tsx
libs/components/layout/src/workspace-sidebar/activities/activities.tsx
libs/components/layout/src/workspace-sidebar/page-tree/DndTree.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/TreeItem.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/tree-item.module.scss

for https://github.com/toeverything/AFFiNE/issues/33

opti: 1.adjust layout style;

---

apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
libs/components/common/src/lib/text/plugins/link.tsx
libs/components/editor-blocks/src/blocks/group/GroupView.tsx
libs/components/editor-blocks/src/blocks/group/components/Panel.tsx
libs/components/editor-plugins/src/comment/Container.tsx
libs/components/editor-plugins/src/menu/command-menu/Container.tsx
libs/components/editor-plugins/src/menu/inline-menu/Container.tsx
libs/components/editor-plugins/src/menu/reference-menu/Container.tsx
libs/components/editor-plugins/src/search/Search.tsx
libs/components/layout/src/header/EditorBoardSwitcher/StatusIcon.tsx
libs/components/layout/src/settings-sidebar/Comments/CommentItem.tsx
libs/components/ui/src/cascader/Cascader.tsx
libs/components/ui/src/popover/Container.tsx
libs/components/ui/src/select/Select.tsx
libs/components/ui/src/theme/theme.ts

fix: lighter box shadow

---

apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
libs/components/layout/src/workspace-sidebar/activities/activities.tsx
libs/datasource/db-service/src/services/workspace/user-config.ts

see https://github.com/toeverything/AFFiNE/issues/76

fixbug: [issue76]when click activities button, throw error;

---

libs/components/layout/src/settings-sidebar/Settings/use-settings.ts

We are still thinking about what the reading mode should look like

fix: disable reading mode

---

libs/components/editor-blocks/package.json
libs/components/editor-blocks/src/blocks/code/CodeView.tsx
pnpm-lock.yaml

Adds support for elixir code highlighting in the code block component.

feat(component): add support for elixir highlighting in code block

---

apps/ligo-virgo/webpack.config.js
apps/venus/webpack.config.js

Have two conditional making the same thing, it's redundant.
Removed one conditional

refactor : remove redundant if

---

apps/keck/src/index.ts
apps/ligo-virgo/src/pages/workspace/Home.tsx
apps/ligo-virgo/src/pages/workspace/docs/workspace-name.tsx

I'm trying minize the repetition and performance of code
while i don't understand all the business rules, i'll adjust others things

Refactor : applyed good practices

---

libs/components/editor-blocks/src/blocks/code/CodeView.tsx

clean up codeblock component
ts types
remove commented code
remove unused vars
better css names
https://www.loom.com/share/baa37adcde2449aa883f783c7ca42e7c

refactor(component): clean up code block component

---

apps/ligo-virgo/src/pages/workspace/docs/components/logo/Logo.tsx
apps/ligo-virgo/src/pages/workspace/docs/components/tabs/Tabs.tsx

fix: props format with errors are shown in the console

---

apps/venus/src/app/index.tsx

Beautify the style of the header,Make the header look bigger and more intuitive

feat/beautify the style of the VenusContainer

---

apps/ligo-virgo-e2e/src/support/app.po.ts

Fix https://github.com/toeverything/AFFiNE/pull/153 https://github.com/toeverything/AFFiNE/pull/154

chore: update cypress element getter

---

libs/components/editor-plugins/src/menu/reference-menu/Container.tsx
libs/components/editor-plugins/src/menu/reference-menu/Plugin.tsx
libs/components/editor-plugins/src/menu/reference-menu/ReferenceMenu.tsx
libs/components/editor-plugins/src/menu/reference-menu/index.ts

- cleaning side effect
- migrate to styled
- render by `PluginRenderRoot`

fix: cleaning ReferenceMenuPlugin side effect

---

apps/ligo-virgo/src/pages/workspace/docs/components/tabs/Tabs.tsx
libs/components/layout/src/header/LayoutHeader.tsx
libs/components/layout/src/settings-sidebar/ContainerTabs/ContainerTabs.tsx
libs/components/layout/src/settings-sidebar/Settings/SettingsPanel.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/TreeItem.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/tree-item.module.scss

see [issue#146](https://github.com/toeverything/AFFiNE/issues/146)

opti: 1.page tree; 2. icon invert; 3.topbar;

---

.github/workflows/check.yml
libs/components/editor-blocks/src/blocks/page/PageView.tsx
libs/components/editor-plugins/src/menu/command-menu/Menu.tsx
libs/components/editor-plugins/src/menu/inline-menu/Container.tsx

fix https://github.com/toeverything/AFFiNE/issues/115

fix page title tranform

---

libs/components/editor-blocks/src/blocks/group/scene-kanban/CardContainer.tsx

Fix https://github.com/toeverything/AFFiNE/issues/29

fix: cancel kanban mouse down event

---

apps/ligo-virgo/src/pages/workspace/docs/components/tabs/Tabs.tsx
libs/components/layout/src/header/EditorBoardSwitcher/StatusIcon.tsx
libs/components/layout/src/header/EditorBoardSwitcher/StatusText.tsx
libs/components/layout/src/header/EditorBoardSwitcher/StatusTrack.tsx
libs/components/layout/src/header/EditorBoardSwitcher/Switcher.tsx
libs/components/layout/src/header/LayoutHeader.tsx

fix https://github.com/toeverything/AFFiNE/issues/176

opti: 1.right panel trigger button cannot click#176;

---

libs/components/editor-core/src/editor/commands/block-commands.ts
libs/components/editor-core/src/editor/drag-drop/drag-drop.ts
libs/components/editor-plugins/src/menu/command-menu/Menu.tsx
libs/components/editor-plugins/src/menu/left-menu/LeftMenuPlugin.tsx

add new grid drop logic、if has no parent grid create grid others create a grid item

feat: new grid drop logic

---

apps/ligo-virgo/src/pages/workspace/docs/components/tabs/Tabs.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/styles.ts

fix https://github.com/toeverything/AFFiNE/issues/184

fix: console error

---

libs/components/board-state/src/tldraw-app.ts

fix https://github.com/toeverything/AFFiNE/issues/135
fix partial of https://github.com/toeverything/AFFiNE/issues/186

Fix: windows zoom

---

apps/ligo-virgo/src/pages/workspace/docs/collapsible-page-tree.tsx
apps/ligo-virgo/src/pages/workspace/docs/workspace-name.tsx
libs/components/common/src/lib/collapsible-title/index.tsx
libs/components/layout/src/header/EditorBoardSwitcher/StatusTrack.tsx
libs/components/layout/src/header/LayoutHeader.tsx
libs/components/layout/src/workspace-sidebar/activities/activities.tsx
libs/components/layout/src/workspace-sidebar/dot-icon/DotIcon.tsx
libs/components/layout/src/workspace-sidebar/dot-icon/index.ts
libs/components/layout/src/workspace-sidebar/page-tree/DndTree.tsx
libs/components/layout/src/workspace-sidebar/page-tree/PageTree.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/TreeItem.tsx
libs/components/layout/src/workspace-sidebar/page-tree/tree-item/styles.ts

see https://github.com/toeverything/AFFiNE/issues/148

improvement: 1.left toolbar hover style#148;

---

libs/components/board-draw/src/TlDraw.tsx
libs/components/board-state/src/tldraw-app.ts
libs/components/board-tools/src/hand-draw/hand-draw-tool.ts
libs/components/board-types/src/types.ts
libs/components/editor-plugins/src/menu/left-menu/LeftMenuPlugin.tsx

feat(whiteboard): cursor style when dragging

---

libs/components/editor-blocks/src/blocks/todo/CheckBox.tsx

fix: type error

---

libs/components/editor-blocks/src/blocks/grid/Grid.tsx
libs/components/editor-core/src/editor/selection/selection.ts

repair grid border in selection

feat: repair grid border in selection

---

libs/components/editor-blocks/src/utils/WithTreeViewChildren.tsx

chore: align tree line

---

libs/components/editor-core/src/Selection.tsx

fix select blocks when mouse wheel after a select

feat: fix selection on scroll

---

README.md

fix: add star badge & add link to contributor badge

---

libs/components/editor-blocks/src/utils/WithTreeViewChildren.tsx

chore: tweak styles

---

README.md

feat: add website badge & update star badge & update contributors badge

---

libs/components/editor-core/src/editor/clipboard/paste.ts

1. Fixed thorw error if pasted last block is not support edit
2. Fixed if focus block is empty, new pasted block will insert after it not replace it

feat: update paste behavior

---

libs/datasource/db-service/src/services/editor-block/templates/get-started-group1.json

fix: update default status color

---

libs/components/editor-plugins/src/menu/left-menu/LeftMenu.tsx

When i create a code or media block, cant add below block easily.
The PR adds a left menu option to add a below block.

feature: add a left menu option to add a below block

---

apps/ligo-virgo/src/pages/workspace/Home.tsx
libs/datasource/db-service/src/services/editor-block/templates/get-started-group1.json
libs/datasource/db-service/src/services/editor-block/templates/get-started-group2.json
libs/datasource/db-service/src/services/editor-block/templates/template-factory.ts

Add a section about how to save changes.

fix: update get-started template

---

apps/venus/src/app/index.tsx

Add the "to" preposition for the sentence to make more grammatical sense

Update grammar in index.tsx

---

libs/components/board-draw/src/components/tools-panel/ToolsPanel.tsx
libs/components/board-state/src/tldraw-app.ts
libs/components/board-tools/src/hand-drag/hand-drag-tool.ts
libs/components/board-tools/src/hand-drag/index.ts
libs/components/board-tools/src/hand-draw/index.ts
libs/components/board-tools/src/index.ts
libs/components/board-types/src/types.ts

related issue: https://github.com/toeverything/AFFiNE/issues/199

fix edgeless edit bar tooltip

---

libs/components/editor-core/src/block-pendant/BlockPendantProvider.tsx
libs/components/editor-core/src/block-pendant/pendant-history-panel/PendantHistoryPanel.tsx
libs/components/editor-core/src/block-pendant/pendant-render/PandentRender.tsx

fix: the pendant popover is blocked by the container in kanban mode

---

libs/components/editor-blocks/src/blocks/bullet/BulletView.tsx
libs/components/editor-blocks/src/blocks/numbered/NumberedView.tsx
libs/components/editor-blocks/src/blocks/text/TextView.tsx
libs/components/editor-blocks/src/blocks/todo/TodoView.tsx
libs/components/editor-blocks/src/utils/indent.ts

Handle indent behavior with root id

fix: handle root block when indent

---

libs/components/editor-plugins/src/menu/group-menu/GropuMenu.tsx

remove line after drop
Close: #234

fix(libs): remove line after drop

---

libs/components/board-shapes/src/editor-util/EditorUtil.tsx

feat(whiteboard): activate text on dblclick

---

.all-contributorsrc
README.md

docs: update contributors

---

README.md

add conatct email address-Update README.md

---

apps/ligo-virgo/src/pages/workspace/docs/Page.tsx
libs/components/ui/src/theme/theme.ts

fix: update sidebar shadow

---

libs/components/editor-core/src/render-block/Context.tsx
libs/components/editor-core/src/render-block/WithTreeViewChildren.tsx

fix unexpected tree line in kanban

fix: kanban tree view

---

libs/components/editor-core/src/editor/editor.ts
libs/components/editor-core/src/editor/keyboard/keyboard.ts

- Update hotkey scope
- Fix hotkey no works after switch to edgeless mode
Maybe fix https://github.com/toeverything/AFFiNE/issues/137 https://github.com/toeverything/AFFiNE/issues/347

fix(keyboard): hotkey unbind incorrect

---

docs/CONTRIBUTING.md

Discord link added & a typo fix.

CONTRIBUTING.md file updated

---

libs/components/editor-blocks/src/components/text-manage/TextManage.tsx
libs/components/editor-core/src/editor/selection/selection.ts
libs/components/editor-plugins/src/menu/inline-menu/menu-item/IconItem.tsx

* fix(select): group selecet
* fix(selection): more robust
* refactor(selection): better group
Co-authored-by: DarkSky <25152247+darkskygit@users.noreply.github.com>

Fix/group select (#378)

---

.github/deployment/Dockerfile-affine
.github/deployment/Dockerfile-affine-keck
.github/deployment/Dockerfile-keck
.github/deployment/Dockerfile-lisa
.github/deployment/Dockerfile-venus

ci: :rocket: Optimize the docker file to use the build cache

---

.github/workflows/languages-download.yml

See https://github.com/toeverything/AFFiNE/pull/409

fix: ci permission

---

apps/venus/src/app/i18n/resources/es.json

fix: update venus spanish language
Co-authored-by: DarkSky <25152247+darkskygit@users.noreply.github.com>

Fix/venus spanish (#423)

---

README.md
docs/types-of-contributions.md

Updated the internationalization section.

GitHub Doc Updates

---

apps/venus/src/app/common/Header.tsx
apps/venus/src/app/common/MobileHeader.tsx
libs/components/layout/src/settings-sidebar/Settings/SettingsList.tsx

* fix: default language
* feat: mobile support multiple languages

fix(i18n): default language select (#450)

---

libs/datasource/db-service/src/services/database/index.ts

Fix https://github.com/toeverything/AFFiNE/issues/449

Fix: window.client.inspect not found

---

libs/datasource/db-service/src/services/database/index.ts

fix: window.client.inspect not found

Fix: window.client.inspect not found (#452)

---

apps/ligo-virgo/webpack.config.js

Fix https://github.com/toeverything/AFFiNE/discussions/448

fix: ignore node_modules watcher

---

libs/components/editor-blocks/src/blocks/group/scene-kanban/CardItem.tsx
libs/components/editor-blocks/src/components/upload/upload.tsx

fix: show up image menu option

---

libs/components/editor-blocks/src/components/upload/upload.tsx

Redesign https://github.com/toeverything/AFFiNE/pull/464
https://user-images.githubusercontent.com/18554747/192792892-c20220a7-82d4-4e06-9829-cf02f17cb1ae.mov

fix: upload layer incorrect

---

libs/components/layout/src/header/LayoutHeader.tsx
libs/components/layout/src/header/Logo/InfoModal.tsx
libs/components/layout/src/header/Logo/ModalContent.tsx

fix: livedemo infomation color & copies

---

libs/components/editor-core/src/editor/commands/block-commands.ts
libs/components/editor-plugins/src/menu/left-menu/LeftMenu.tsx
libs/components/editor-plugins/src/menu/left-menu/LeftMenuDraggable.tsx

#471 try solve the first issue in it

fix: delete block leftMenu not delete

---

docs/jobs/affine.pro-remote.md
docs/jobs/affine.pro.md

- Minor edits
- Added contact address
- Added fully-remote job

Jobs updated

---

apps/venus/src/app/common/Footer.tsx
libs/components/editor-core/src/editor/editor.ts
libs/components/layout/src/header/Logo/InfoModal.tsx

fix: update copyright info

---

packages/app/next.config.js
packages/app/scripts/gitInfo.js
packages/app/src/pages/_app.tsx
packages/app/src/utils/print-build-info.ts

chore: print build info

---

packages/app/next.config.js
packages/app/package.json
packages/logger/package.json
packages/logger/tsconfig.json
pnpm-lock.yaml

Upgrade next.js to v13
More details see https://nextjs.org/docs/upgrading#upgrading-from-12-to-13

chore: upgrade next to v13

---

.github/workflows/playwright.yml
.gitignore
.vscode/settings.json
package.json
packages/app/src/components/theme-mode-switch/index.tsx
playwright.config.ts
pnpm-lock.yaml
tests/theme.spec.ts

This pr just setup e2e environment. More test cases will be added later.

chore: add e2e

---

packages/app/src/components/workspace-slider-bar/style.ts

Before:
https://user-images.githubusercontent.com/14026360/209060238-1c1b0f02-d097-44fc-b7ab-fc648c70d2d3.mov
After:
https://user-images.githubusercontent.com/14026360/209060261-5d88ec4e-aa47-48fc-9e94-de107d05234f.mov

fix: relative position of StyledArrowButton

---

packages/app/src/globals.d.ts
packages/app/src/pages/workspace/[workspaceId]/[pageId].tsx

Improve https://github.com/toeverything/AFFiNE/pull/590

chore: improve types for markdown

---

packages/app/src/ui/button/button.tsx

hide button content when button is show loading

feat: fix show content when loading

---

packages/app/src/components/workspace-slider-bar/index.tsx
packages/app/src/components/workspace-slider-bar/style.ts
tests/layout.spec.ts

https://user-images.githubusercontent.com/102217452/210030253-82af7c17-6766-49cc-a260-317fcac1f745.mov

chore: update quick search style of  slider bar

---

packages/app/src/components/quick-search/style.ts

fix: quick search style bug

---

packages/app/package.json
pnpm-lock.yaml

Related: https://github.com/yjs/yjs/issues/438

chore: bump version

---

packages/app/package.json
packages/data-center/package.json
packages/data-center/src/datacenter.ts
pnpm-lock.yaml

For anyone who want to enable any flags, you can do it on the console
```js
workspace.meta.awareness.setFlag('enable_drag_handle', true)
```
Upstream: https://github.com/toeverything/blocksuite/pull/658

feat: support flags in workspace

---

.github/CODEOWNERS
.github/workflows/languages-sync.yml
packages/i18n/README.md
packages/i18n/src/resources/en.json

When the en.json(base language) updated and merged to the develop branch, will trigger the languages-sync action.
The languages-sync action will check the base language and add missing translations to the Tolgee platform.
This way, partners from the community can update the translations.

feat: add i18n keys auto sync

---

packages/app/src/components/workspace-modal/index.tsx
packages/app/src/components/workspace-slider-bar/index.tsx

Remove temporary language toggle button from sidebar and add toggle button in workspace mode.

feat: add language switch in workspace modal

---

packages/app/src/pages/workspace/[workspaceId]/[pageId].tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/745

fix: listen on title change

---

packages/app/src/components/editor/index.tsx
packages/app/src/templates/Welcome-to-AFFiNE-Alpha-Downhills.md

fix: fix the typo of downhills

---

.github/ISSUE_TEMPLATE.md

chore: add community link to template

---

playwright.config.ts
playwright.config.unit.ts

See https://playwright.dev/docs/test-reporters#github-actions-annotations

feat: enable github reporter

---

packages/app/package.json
packages/data-center/package.json
pnpm-lock.yaml

Fixes: https://github.com/toeverything/blocksuite/issues/1014

fix: import blocksuite twice

---

packages/app/src/components/quick-search/index.tsx
packages/app/src/components/quick-search/style.ts
tests/quick-search.spec.ts

fix: update search UI in public page

---

packages/app/src/components/workspace-modal/SelectLanguageMenu.tsx
packages/i18n/src/index.ts
tests/local-first-workspace.spec.ts

fix: retrieves missing default language

---

packages/data-center/src/provider/local/local.ts

fix: local cache not work in creation

---

packages/app/src/pages/invite/[invite_code].tsx

fix: inviting page add loading to wait request

---

packages/app/src/components/workspace-modal/WorkspaceCard.tsx

fix: workspace type wrong

---

packages/data-center/src/provider/affine/affine.ts

fix: add collabration name

---

packages/app/src/components/editor/index.tsx
packages/app/src/pages/404.tsx
packages/app/src/pages/_app.tsx
packages/app/src/pages/workspace/[workspaceId]/[pageId].tsx
packages/app/src/pages/workspace/[workspaceId]/all.tsx
packages/app/src/pages/workspace/[workspaceId]/favorite.tsx
packages/app/src/pages/workspace/[workspaceId]/setting.tsx
packages/app/src/pages/workspace/[workspaceId]/trash.tsx

fix https://github.com/toeverything/AFFiNE/issues/854

fix: add page titles

---

packages/app/src/pages/_app.tsx

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

fix: html tag should have correct lang attr

---

packages/data-center/src/provider/affine/__tests__/mock-apis.ts
packages/data-center/src/provider/affine/affine.ts
packages/data-center/src/provider/affine/apis/__tests__/auth.spec.ts
packages/data-center/src/provider/affine/apis/auth.ts
packages/data-center/src/provider/affine/apis/index.ts
packages/data-center/src/provider/affine/apis/request.ts
packages/data-center/src/provider/affine/apis/token.ts
packages/data-center/src/provider/affine/apis/workspace.ts
packages/data-center/src/provider/affine/channel.ts
packages/data-center/src/provider/affine/storage.ts

refactor: token handling

---

apps/web/src/providers/app-state-provider/Provider.tsx

fix https://github.com/toeverything/AFFiNE/issues/964

fix: userInfo being initialized correctly

---

apps/web/src/hooks/use-public-workspace.ts
apps/web/src/pages/public-workspace/[workspaceId]/[pageId].tsx
apps/web/src/pages/public-workspace/[workspaceId]/index.tsx

fix https://github.com/toeverything/AFFiNE/issues/907

fix: should show workspace avatar using blob url

---

apps/web/src/pages/workspace/[workspaceId]/setting.tsx

Sync is not in scope for current version.

fix: hide sync tab for web version

---

apps/web/src/components/enable-workspace-modal/index.tsx
apps/web/src/components/enable-workspace-modal/style.ts
apps/web/src/components/workspace-layout/index.tsx
apps/web/src/components/workspace-modal/styles.ts
apps/web/src/hooks/use-ensure-workspace.ts
apps/web/src/providers/app-state-provider/Provider.tsx
apps/web/src/providers/app-state-provider/interface.ts
apps/web/src/store/globalModal/index.tsx
packages/component/src/ui/modal/ModalWrapper.tsx
packages/data-center/src/datacenter.ts
packages/data-center/src/provider/affine/affine.ts
packages/data-center/src/provider/affine/apis/auth.ts
packages/data-center/src/provider/affine/apis/request.ts
packages/data-center/src/provider/affine/utils.ts
packages/data-center/src/workspace-unit-collection.ts
packages/data-center/src/workspace-unit.ts

please refer to the commit list for all the changes.
This pr should also fix https://github.com/toeverything/AFFiNE/issues/968

fix: some login & enable affine cloud issues

---

apps/web/src/components/workspace-slider-bar/WorkspaceSelector/WorkspaceSelector.tsx
apps/web/src/providers/app-state-provider/utils.ts
tests/local-first-workspace.spec.ts

chore: change default Workspace name to "Demo Workspace"

---

packages/component/src/ui/button/styles.ts

fix: Button UI issues

---

apps/web/src/providers/ThemeProvider.tsx
packages/component/src/styles/utils/localStorageThemeHelper.ts

Closes: https://github.com/toeverything/AFFiNE/pull/1103

feat: read local theme on page load

---

apps/web/src/pages/temporary.css

See https://github.com/toeverything/blocksuite/pull/1240
Please merge this PR after bump blocksuite version

chore: remove workaround margin

---

apps/web/src/components/workspace-modal/styles.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1143

fix: use css `first-child`

---

apps/web/src/components/workspace-setting/general/delete/Delete.tsx

fix: wrong workspace name when deleting workspace

---

apps/web/src/components/workspace-slider-bar/DragLine.tsx
apps/web/src/components/workspace-slider-bar/index.tsx
apps/web/src/components/workspace-slider-bar/style.ts

Close [#1183](https://github.com/toeverything/AFFiNE/issues/1183)

feat: support sidebar zoom

---

apps/web/src/components/message-center-handler/index.tsx
packages/data-center/src/message/code.ts
packages/data-center/src/provider/affine/apis/google.ts
packages/data-center/src/provider/affine/apis/request-error.ts
packages/data-center/src/provider/affine/apis/workspace.ts

fix: [#1193](https://github.com/toeverything/AFFiNE/issues/1193)

fix: stay loading when refresh token  fail

---

packages/data-center/src/provider/affine/apis/google.ts

https://firebase.google.com/docs/emulator-suite/connect_auth

feat: connect firebase emulator

---

apps/web/src/components/workspace-setting/member/InviteMemberModal.tsx

fix: always show email tip

---

apps/web/src/components/blocksuite/block-suite-page-list/page-list/index.tsx
tests/local-first-favorites-items.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1225

fix: favorite button will not work

---

apps/web/src/pages/workspace/[workspaceId]/[pageId].tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1230

fix: set BlockSuite flags

---

apps/web/src/components/pure/quick-search-modal/Footer.tsx
apps/web/src/hooks/use-workspaces.ts
apps/web/src/layouts/index.tsx
apps/web/src/plugins/local/index.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1233

refactor: use nano id

---

apps/web/src/atoms/index.ts
apps/web/src/atoms/public-workspace/index.ts
apps/web/src/hooks/use-workspaces.ts
apps/web/src/pages/_debug/broadcast.dev.tsx
apps/web/src/pages/preview/[previewId].tsx
apps/web/src/plugins/local/index.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1285

fix: blob fetch and state syncing between tabs

---

apps/web/package.json
packages/component/package.json
pnpm-lock.yaml

Fixes: https://github.com/toeverything/AFFiNE/issues/1312

chore: fix peer dependencies

---

apps/web/src/components/affine/workspace-setting-detail/panel/general/delete/index.tsx
apps/web/src/components/affine/workspace-setting-detail/panel/general/index.tsx
apps/web/src/providers/ModalProvider.tsx
tests/libs/sidebar.ts
tests/local-first-delete-workspace.spec.ts

Related: https://github.com/toeverything/AFFiNE/issues/1316

fix: always show workspace list modal when no workspaces

---

apps/web/src/atoms/index.ts
apps/web/src/components/pure/quick-search-modal/Results.tsx
apps/web/src/components/pure/workspace-slider-bar/index.tsx
apps/web/src/hooks/__tests__/index.spec.tsx
apps/web/src/hooks/affine/use-recent-views.ts
apps/web/src/pages/workspace/[workspaceId]/[pageId].tsx

feat: add recentlyViewed 

---

apps/web/src/components/pure/contact-modal/index.tsx

FIxes: https://github.com/toeverything/AFFiNE/issues/1348, https://github.com/toeverything/AFFiNE/issues/1346

fix: about us modal

---

apps/web/src/components/blocksuite/header/editor-mode-switch/index.tsx
tests/change-page-mode.spec.ts

Fixes toeverything/AFFiNE#1342
- Update  "Paper" by "Page" title.

fix: update title on tab

---

apps/web/src/hooks/affine/use-toggle-workspace-publish.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1347

fix: public workspace state

---

apps/web/src/components/blocksuite/block-suite-page-list/page-list/DateCell.tsx
apps/web/src/components/blocksuite/block-suite-page-list/page-list/index.tsx
apps/web/src/components/blocksuite/header/header-right-items/EditorOptionMenu.tsx
apps/web/src/hooks/use-page-meta.ts

fix: Add the trashDate field whenever a page is moved to the trash.

---

apps/web/src/components/blocksuite/block-suite-page-list/page-list/OperationCell.tsx
packages/i18n/src/resources/en.json
tests/local-first-delete-page.spec.ts
tests/local-first-restore-page.spec.ts
tests/local-first-show-delete-modal.spec.ts
tests/local-first-trash-page.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1386

fix: add key 'Move to Trash'

---

apps/web/src/components/blocksuite/header/header-right-items/theme-mode-switch/index.tsx
apps/web/src/components/blocksuite/header/header-right-items/theme-mode-switch/style.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1343

fix: theme button

---

apps/web/src/pages/invite/[invite_code].tsx
apps/web/src/plugins/affine/fetcher.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1353

fix: add invitation page

---

apps/web/src/components/blocksuite/header/header-right-items/EditorOptionMenu.tsx
apps/web/src/components/blocksuite/header/header-right-items/SyncUser.tsx
apps/web/src/components/blocksuite/header/header-right-items/theme-mode-switch/index.tsx
apps/web/src/components/blocksuite/header/header-right-items/theme-mode-switch/style.ts
packages/component/src/ui/menu/MenuItem.tsx

fix: ui issues

---

apps/web/src/components/affine/workspace-setting-detail/index.tsx
apps/web/src/components/affine/workspace-setting-detail/panel/collaboration/index.tsx
apps/web/src/components/affine/workspace-setting-detail/panel/publish/index.tsx
apps/web/src/components/blocksuite/header/header-right-items/SyncUser.tsx
apps/web/src/hooks/use-transform-workspace.ts
apps/web/src/pages/_app.tsx
apps/web/src/pages/workspace/[workspaceId]/all.tsx
apps/web/src/pages/workspace/[workspaceId]/setting.tsx
apps/web/src/plugins/affine/index.tsx
apps/web/src/plugins/index.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1349

refactor: add hook transform workspace

---

apps/web/package.json
apps/web/src/components/page-detail-editor.tsx
apps/web/src/layouts/index.tsx
apps/web/src/pages/404.tsx
apps/web/src/pages/_app.tsx
apps/web/src/pages/workspace/[workspaceId]/favorite.tsx
apps/web/src/pages/workspace/[workspaceId]/setting.tsx
apps/web/src/pages/workspace/[workspaceId]/trash.tsx
pnpm-lock.yaml

Fixes: https://github.com/toeverything/AFFiNE/issues/1369

refactor: remove `react-helmet-async`

---

apps/web/src/components/affine/workspace-setting-detail/panel/collaboration/index.tsx

fix: button "jumps" between workplace settings tabs

---

apps/web/src/components/pure/quick-search-modal/Results.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1417

fix: ignore trash

---

apps/web/src/providers/ModalProvider.tsx
packages/component/src/ui/modal/Modal.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1185

fix: infinite workspace loading

---

docs/BUILDING.md
docs/building-desktop-client-app.md

preview: https://github.com/toeverything/AFFiNE/blob/docs/client-app/docs/building-desktop-client-app.md

docs: add dev/build docs for tauri app

---

apps/web/src/plugins/affine/index.tsx
apps/web/src/plugins/index.tsx
apps/web/src/providers/ModalProvider.tsx

Fixme: https://github.com/toeverything/AFFiNE/issues/1381

fix: cleanup data when logout

---

apps/web/src/components/pure/quick-search-modal/index.tsx

fix: can't open quick search without cursor

---

apps/web/src/components/pure/workspace-slider-bar/index.tsx
apps/web/src/components/pure/workspace-slider-bar/style.ts

fix: fixed the issue of text being squeezed in the sidebar animation

---

packages/component/src/ui/table/styles.ts

fix: support min width for workspace list table

---

apps/web/src/components/affine/workspace-setting-detail/index.tsx
apps/web/src/components/affine/workspace-setting-detail/panel/sync/index.tsx
apps/web/src/shared/index.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1475

feat: add sync panel

---

apps/web/src/components/pure/message-center/index.tsx
apps/web/src/pages/_app.tsx
packages/data-center/src/index.ts
packages/data-center/src/message/code.ts
packages/data-center/src/message/message.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/1483

feat: add message center

---

apps/web/src/components/pure/quick-search-modal/Results.tsx

fix: recent still show when recent is empty

---

apps/web/src/templates/Welcome-to-AFFiNE.md

docs: pre-load content update image

---

apps/web/src/components/blocksuite/header/index.tsx
apps/web/src/components/blocksuite/header/styles.ts

feat: center title

---

apps/web/src/components/blocksuite/header/editor-mode-switch/switch-items.tsx

https://github.com/chenqingspring/react-lottie/issues/51

fix: lottie import logic

---

packages/env/src/ua-helper.ts

fix: wrong OS judgment

---

apps/web/src/providers/ThemeProvider.tsx
packages/component/src/ui/button/styles.ts
packages/component/src/ui/menu/styles.ts

fix: error initial style when first in dark mode

---

apps/web/src/components/affine/workspace-setting-detail/panel/publish/index.tsx

close https://github.com/toeverything/AFFiNE/issues/1549

fix: duplicate enable cloud confirm modal after enable

---

apps/web/src/components/pure/quick-search-modal/index.tsx
apps/web/src/components/pure/quick-search-modal/style.ts
packages/component/src/ui/modal/ModalWrapper.tsx

chore: update quick search style

---

apps/web/src/atoms/index.ts
apps/web/src/components/blocksuite/header/header.tsx
apps/web/src/components/blocksuite/header/index.tsx
apps/web/src/components/page-detail-editor.tsx
apps/web/src/hooks/use-workspaces.ts
packages/component/src/components/block-suite-editor/index.tsx
tests/local-first-favorites-items.spec.ts

Fix https://github.com/toeverything/AFFiNE/issues/1566
https://user-images.githubusercontent.com/18554747/225008475-88ff1822-b65a-4dc4-b166-f94e40cafb72.mov

fix: quick search tips follow when resize

---

.github/workflows/client-app.yml
apps/electron/layers/main/src/main-window.ts
apps/electron/layers/main/src/protocol.ts

- fix reload app issue
- fix preload not working issue

fix: electron preload issue

---

apps/web/src/components/pure/workspace-slider-bar/index.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1592

fix: side bar favorited list cannot scroll

---

.github/workflows/client-app.yml
apps/electron/forge.config.js
apps/electron/package.json
apps/electron/scripts/common.mjs
apps/electron/yarn.lock
pnpm-workspace.yaml

- make windows build work
- add windows release workflow
- fix MacOS intel release version not working

feat: make electron windows build

---

.github/workflows/client-app.yml

turns out this issue can be easily identified by gpt

fix: window release

---

apps/web/src/components/affine/workspace-setting-detail/panel/general/delete/index.tsx
apps/web/src/components/pure/create-workspace-modal/index.tsx
packages/component/src/ui/input/Input.tsx

Upstream: https://github.com/toeverything/AFFiNE/pull/1610

fix: autofocus

---

packages/env/src/constant.ts
packages/workspace/src/affine/__tests__/api.spec.ts
packages/workspace/src/affine/api/index.ts

Related: https://github.com/toeverything/AFFiNE/issues/1707

feat: detect if blob too large

---

apps/web/src/layouts/styles.ts

fix https://github.com/toeverything/AFFiNE/issues/1765#event-8893488456

fix: blockhub position

---

packages/i18n/src/resources/en.json

chore: update sentence

---

.github/workflows/release-desktop-app.yml
apps/electron/forge.config.js
apps/electron/package.json
apps/electron/scripts/generate-assets.mjs
docs/building-desktop-client-app.md

- cleanup electron build workflow
- update build docs

fix: cleanup electron build script

---

packages/component/src/styles/theme.ts

related to https://github.com/toeverything/blocksuite/issues/1961

feat: update code-block background color

---

packages/component/src/components/block-suite-editor/index.tsx

related to https://github.com/toeverything/blocksuite/issues/1967

fix: enable autofocus in blocksuite editor

---

.github/workflows/release-desktop-app.yml

fix: https://github.com/toeverything/AFFiNE/issues/1853
https://github.com/toeverything/AFFiNE/actions/runs/4650956111

ci: fix windows build artifacts path name error

---

apps/web/src/components/page-detail-editor.tsx
apps/web/src/components/pure/help-island/index.tsx
apps/web/src/layouts/index.tsx
apps/web/src/layouts/public-workspace-layout.tsx
apps/web/src/pages/_debug/init-page.dev.tsx
apps/web/src/pages/_debug/login.dev.tsx
apps/web/src/pages/public-workspace/[workspaceId].tsx
apps/web/src/providers/ModalProvider.tsx

https://twitter.com/himseIf_65/status/1646171194964561920?s=20

refactor: remove next/dynamic

---

apps/web/src/components/page-detail-editor.tsx

Related: https://github.com/toeverything/AFFiNE/issues/1897

fix: use `startTransition`

---

apps/web/src/components/affine/pinboard/pinboard-render/OperationButton.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1898
Removed the logic of onMouseLeave, the logic of clicking to open and clicking to close is clearer.

fix: improve UX of dropdown

---

apps/web/src/components/page-detail-editor.tsx
apps/web/src/components/pure/help-island/index.tsx
apps/web/src/layouts/index.tsx
apps/web/src/layouts/public-workspace-layout.tsx
apps/web/src/pages/_debug/init-page.dev.tsx
apps/web/src/pages/_debug/login.dev.tsx
apps/web/src/pages/public-workspace/[workspaceId].tsx
apps/web/src/providers/ModalProvider.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/1906

fix: wrap React.lazy with Suspense

---

apps/electron/layers/main/src/app-state/google-auth.ts
apps/electron/layers/main/src/app-state/index.ts
apps/electron/layers/main/src/protocol.ts
apps/electron/layers/preload/preload.d.ts
apps/electron/layers/preload/src/index.ts
apps/web/src/plugins/affine/index.tsx
packages/workspace/src/affine/login.ts

fix https://github.com/toeverything/AFFiNE/issues/1911

fix: failed to load blobs in electron

---

.github/CLA.md

docs: update CLA.md

---

.github/workflows/build-master.yml
.github/workflows/build.yml
scripts/wait-3000-healthz.mjs
tests/parallels/open-affine.spec.ts

Related: https://github.com/toeverything/AFFiNE/issues/1952

test: fix flaky

---

apps/electron/layers/main/src/app-state/index.ts
apps/electron/layers/main/src/main-window.ts

fix https://github.com/toeverything/AFFiNE/issues/1939

fix: fix windows build client error and release cannot open

---

apps/web/package.json
apps/web/src/components/affine/sidebar-switch/index.tsx
apps/web/src/components/blocksuite/workspace-header/header.tsx
apps/web/src/components/pure/workspace-slider-bar/index.tsx
apps/web/src/hooks/use-sidebar-status.ts
yarn.lock

Upstream: https://github.com/mui/material-ui/issues/35891

fix: hydration error

---

.github/CLA.md

docs: sign CLA

---

packages/component/src/components/block-suite-editor/index.tsx
packages/component/src/theme/global.css
tests/parallels/change-page-mode.spec.ts

fix(web): remove edgeless mode padding

---

apps/web/src/components/affine/sidebar-switch/index.tsx
apps/web/src/components/pure/workspace-slider-bar/index.tsx

feat: add short cuts for sidebar

---

apps/web/src/components/pure/workspace-slider-bar/changeLog/index.tsx
apps/web/src/components/pure/workspace-slider-bar/shared-styles.ts
packages/component/src/components/changeLog/index.css.ts
packages/component/src/components/changeLog/index.tsx
packages/component/src/stories/ChangeLog.stories.tsx

chore: add changeLog to storybook

---

apps/electron/tests/basic.spec.ts
apps/web/src/atoms/index.ts
apps/web/src/components/affine/tmp-disable-affine-cloud-modal/index.tsx
apps/web/src/components/pure/footer/index.tsx
apps/web/src/providers/ModalProvider.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/2044

feat(electron): enable disable cloud alert

---

packages/theme/src/index.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/2127

fix: shadow theme

---

apps/web/src/components/root-app-sidebar/index.tsx
packages/component/src/components/app-sidebar/index.css.ts
packages/component/src/components/app-sidebar/index.jotai.ts
packages/component/src/components/app-sidebar/index.stories.tsx
packages/component/src/components/app-sidebar/index.tsx
packages/component/src/components/app-sidebar/resize-indicator/index.css.ts
packages/component/src/components/app-sidebar/resize-indicator/index.tsx
playwright.config.ts
tests/parallels/quick-search.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/2194

fix: sidebar regression

---

apps/web/package.json
yarn.lock

Fix https://github.com/jotaijs/jotai-devtools/pull/67

chore: upgrade jotai devtools

---

apps/web/src/components/page-detail-editor.tsx
apps/web/src/hooks/use-sync-router-with-current-page-id.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/2232

fix: cleanup page id in time

---

packages/component/src/components/tour-modal/TourModal.tsx
packages/component/src/components/tour-modal/index.css.ts

chore: optimize onboarding component style

---

apps/web/src/components/blocksuite/workspace-header/header.tsx
apps/web/src/components/blocksuite/workspace-header/styles.ts

https://user-images.githubusercontent.com/102217452/236383993-63092073-889f-4c11-a50e-d626b467ef1f.mov

chore: add border for header when in edgeless page

---

apps/web/src/components/pure/shortcuts-modal/style.ts

fix: background color on shortcuts header

---

apps/web/src/components/affine/tmp-disable-affine-cloud-modal/index.tsx

chore: update AFFiNE Cloud prompt

---

apps/web/src/components/blocksuite/workspace-header/header-right-items/editor-option-menu.tsx

fix: delete modal on confirm does not close

---

packages/component/src/components/tour-modal/index.css.ts
packages/component/src/components/tour-modal/tour-modal.tsx

chore: add animation for tour modal

---

apps/electron/scripts/generate-assets.mjs

depend on internal release version fix, should use semver version
ref: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L388

fix: app updater not working for internal release

---

docs/jobs.md

Add submission methods for resumes.

docs: update jobs.md

---

apps/web/src/components/blocksuite/workspace-header/header-right-items/editor-option-menu.tsx
apps/web/src/components/blocksuite/workspace-header/header-right-items/theme-mode-switch/style.ts

fix: text overflows in the header option menu 

---

packages/component/src/stories/button.stories.tsx
packages/component/src/ui/button/dropdown.tsx
packages/component/src/ui/button/styles.css.ts

https://github.com/toeverything/AFFiNE/assets/18554747/4a40f19d-2871-41ae-b94f-dfe4ba7383df

feat: add dropdown button

---

packages/env/src/blocksuite.ts
packages/templates/src/AFFiNE-beta-0.5.4.md
tests/parallels/affine/affine-public-workspace.spec.ts

Close #2403
https://github.com/toeverything/AFFiNE/assets/102217452/b3de1648-0bd6-4472-9023-d36963434207

chore: update preloading page

---

packages/templates/src/AFFiNE-beta-0.5.4.md

chore: update pre-loading page

---

apps/web/src/components/pure/workspace-slider-bar/favorite/favorite-list.tsx
packages/component/src/components/app-sidebar/index.stories.tsx
packages/component/src/components/app-sidebar/menu-item/index.css.ts
packages/component/src/components/app-sidebar/menu-item/index.stories.tsx
packages/component/src/components/app-sidebar/menu-item/index.tsx
packages/component/src/components/app-sidebar/quick-search-input/index.css.ts
packages/hooks/src/use-block-suite-page-references.ts
tests/libs/page-logic.ts
tests/parallels/local-first-favorites-items.spec.ts

https://github.com/toeverything/AFFiNE/assets/584378/a48b355f-906c-4942-8695-21f9d56415c9

feat: fav page references

---

packages/templates/src/AFFiNE-beta-0.5.4.md

chore: update pre-load content

---

apps/web/src/components/pure/workspace-list-modal/index.tsx
apps/web/src/components/pure/workspace-slider-bar/favorite/favorite-list.tsx
apps/web/src/components/pure/workspace-slider-bar/favorite/styles.css.ts
packages/component/src/components/app-sidebar/add-page-button/index.tsx
packages/component/src/components/app-sidebar/app-updater-button/index.css.ts
packages/component/src/components/app-sidebar/index.css.ts
packages/component/src/components/app-sidebar/menu-item/index.css.ts
packages/component/src/components/app-sidebar/menu-item/index.tsx
packages/component/src/components/app-sidebar/sidebar-containers/index.css.ts
packages/component/src/components/app-sidebar/sidebar-containers/index.tsx
packages/component/src/components/app-sidebar/spolight/index.css.ts
packages/component/src/components/app-sidebar/spolight/index.stories.tsx
packages/component/src/components/app-sidebar/spolight/index.tsx

Some style issues related to sidebar

fix: adjust some styles

---

apps/web/package.json
packages/component/package.json
yarn.lock

chore: bump icon version

---

packages/i18n/src/resources/de.json
packages/i18n/src/resources/en.json
packages/i18n/src/resources/fr.json
packages/i18n/src/resources/ja.json
packages/i18n/src/resources/ru.json
packages/i18n/src/resources/zh-Hans.json

chore: remove unused i18n key

---

README.md

Minor spelling correction in the README.md file.

docs: correct spelling

---

apps/web/src/adapters/affine/index.tsx
apps/web/src/pages/workspace/[workspaceId]/[pageId].tsx
packages/component/src/components/block-suite-editor/index.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/2519

fix: dispose on editor `props.onInit`

---

packages/component/src/components/page-list/all-page.tsx
packages/component/src/components/page-list/use-sorter.ts

Fix https://github.com/toeverything/AFFiNE/issues/1216

fix: sort in desc based update date by default

---

packages/component/src/components/page-list/all-pages-body.tsx
packages/component/src/components/page-list/components/title-cell.tsx
packages/component/src/ui/table/styles.ts

chore: tweak all page styles

---

packages/component/src/ui/button/dropdown.tsx
packages/component/src/ui/button/styles.css.ts

fix: dropdown menu entire right can be pulled down

---

packages/component/package.json
packages/component/src/ui/switch/index.css.ts
packages/component/src/ui/switch/switch.tsx
yarn.lock

https://github.com/toeverything/AFFiNE/assets/102217452/658e4c1a-a727-44d3-bb89-e289604ccb04

chore: adjust switch style

---

apps/web/src/components/blocksuite/block-suite-page-list/index.tsx
apps/web/src/components/pure/workspace-list-modal/styles.ts
packages/component/package.json
packages/component/src/stories/button.stories.tsx
packages/component/src/ui/button/dropdown.tsx
packages/component/src/ui/button/radio.tsx
packages/component/src/ui/button/styles.css.ts
yarn.lock

https://github.com/toeverything/AFFiNE/assets/18554747/937ebbb2-4253-4bd9-9370-f2e6b09a470c
Ref https://www.radix-ui.com/docs/primitives/components/radio-group

feat: add radio group

---

apps/web/src/components/pure/quick-search-modal/results.tsx

fix: quick search result missing title

---

apps/web/src/components/blocksuite/workspace-header/styles.css.ts

Fix https://github.com/toeverything/AFFiNE/issues/2599
Clicking this area may not close the popover

fix: popover may not be closable

---

packages/component/src/components/page-list/all-page.tsx
packages/component/src/components/page-list/all-pages-body.tsx
packages/component/src/components/page-list/utils.tsx
packages/component/src/ui/table/styles.ts

https://github.com/toeverything/AFFiNE/assets/18554747/088b6faa-89d0-4d23-9d0a-0e14e436bd55

fix: update breakpoint in all page

---

apps/web/src/components/blocksuite/workspace-header/header.tsx

Header's component props has error,
fix it

fix(web): header div props error

---

packages/component/src/components/page-list/all-page.tsx
packages/component/src/components/page-list/all-pages-body.tsx
packages/component/src/components/page-list/components/title-cell.tsx
packages/component/src/components/page-list/styles.ts
packages/component/src/components/page-list/type.ts
packages/component/src/stories/page-list.stories.tsx

See also https://github.com/toeverything/AFFiNE/pull/2603

feat: page list supports preview

---

apps/web/src/components/blocksuite/block-suite-page-list/index.tsx
packages/hooks/src/use-block-suite-page-preview.ts

https://github.com/toeverything/AFFiNE/assets/18554747/948a261c-3cbf-4bb7-98b9-f4ea08bbc01b

feat: add page preview

---

apps/web/src/layouts/workspace-layout.tsx

Related to https://github.com/toeverything/AFFiNE/pull/2385

fix: drag delay

---

packages/component/src/components/page-list/components/title-cell.tsx
packages/component/src/components/page-list/view/view-list.css.ts

Work for #2635 
https://github.com/toeverything/AFFiNE/assets/102217452/6f439922-32b8-46da-956a-d2879613da79

chore: update all page style

---

packages/component/src/components/affine-watermark/index.css.ts
packages/component/src/components/page-list/operation-menu-items/export.tsx
packages/component/src/components/workspace/index.css.ts

fix: pdf export in client and hide png export

---

packages/component/src/components/page-list/filter/condition.tsx
packages/component/src/components/page-list/filter/vars.tsx
tests/parallels/all-page.spec.ts

View feature is not yet enabled so there is no View test

test: add some e2e tests for all pages filter

---

packages/component/src/ui/empty/empty-svg.tsx
packages/component/src/ui/empty/empty.tsx

fix: empty icon color error

---

packages/component/src/stories/button.stories.tsx
packages/component/src/ui/button/styles.css.ts

fix: overflow in radio button group

---

apps/web/src/components/pure/workspace-slider-bar/favorite/favorite-list.tsx
tests/parallels/local-first-favorites-items.spec.ts

fix https://github.com/toeverything/AFFiNE/issues/2661

fix: do not show deleted reference

---

packages/component/src/components/workspace/index.css.ts

The top padding should be draggable

fix: the top padding should be draggable

---

apps/electron/layers/main/src/db/__tests__/ensure-db.spec.ts
apps/electron/layers/main/src/db/ensure-db.ts
apps/electron/layers/main/src/db/secondary-db.ts

It seems the our Rust wrapper for SQLite is not working properly.

fix(native): secondary db polling logic

---

packages/env/src/config.ts

Solving ts check problem in preset.config.mjs

fix: add bookmark operation flag for ts check

---

tests/parallels/local-first-workspace-list.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/2722

fix: flaky when drag workspace list

---

apps/web/src/layouts/workspace-layout.tsx

fix: add guide to the other page

---

packages/component/src/components/image-preview-modal/hooks/use-zoom.tsx
packages/component/src/components/image-preview-modal/index.css.ts
packages/component/src/components/image-preview-modal/index.tsx

fix: image preview

---

apps/web/src/components/blocksuite/workspace-header/header.tsx

fix: window control not work

---

plugins/copilot/src/UI/detail-content.tsx
plugins/copilot/src/UI/index.css.ts
plugins/copilot/src/core/components/conversation-list/index.css.ts
plugins/copilot/src/core/components/conversation/index.css.ts
plugins/copilot/src/core/components/following-up/index.css.ts

style: temporarily adjust the style of the co-pilot

---

apps/docs/index.html

Related: https://github.com/dai-shi/waku/issues/83

fix(docs): defer entry js

---

packages/component/src/components/date-picker/index.css.ts
packages/component/src/components/page-list/filter/index.css.ts

Supplement for #2635 
https://github.com/toeverything/AFFiNE/assets/102217452/bc248279-e1e2-43d7-8eda-84b2fb4ad4f2

style: add hover style for filter item

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/release-desktop-app.yml
apps/electron/tests/workspace.spec.ts
apps/web/preset.config.mjs
apps/web/src/atoms/index.ts
apps/web/src/components/affine/create-workspace-modal/index.tsx
apps/web/src/components/affine/workspace-setting-detail/panel/export/index.tsx
apps/web/src/components/affine/workspace-setting-detail/panel/general/index.tsx
apps/web/src/components/pure/workspace-list-modal/index.tsx
nx.json
packages/env/src/config.ts
packages/workspace/src/local/crud.ts
packages/workspace/src/providers/index.ts
tsconfig.json

sqlite provider is not ready (migration). Before that, we will have to disable all sqlite provider related functions.
related to https://github.com/toeverything/AFFiNE/issues/2841

fix: disable sqlite provider

---

.eslintrc.js
apps/server/src/modules/auth/resolver.ts
packages/component/src/components/page-list/__tests__/filter.spec.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/2897

feat: add rule 'sonarjs/no-identical-functions'

---

packages/component/src/components/app-sidebar/app-updater-button/index.css.ts

Keeping up with the latest color scheme

fix: updater color updates

---

apps/electron/src/main/export/pdf.ts
apps/web/src/layouts/workspace-layout.tsx
packages/component/src/components/page-list/operation-menu-items/export.tsx
packages/component/src/components/workspace/index.css.ts

close https://github.com/toeverything/AFFiNE/issues/2778

feat: export page as file

---

packages/component/src/components/notification-center/index.tsx

refactor: fix typo in notification-center/index.tsx

---

packages/env/src/blocksuite/subdoc-migration.ts

fix(web): migrate connector

---

.eslintrc.js
package.json
yarn.lock

Upstream: https://github.com/import-js/eslint-plugin-import/pull/2447#issuecomment-1117384140

chore: replace 'eslint-plugin-import'

---

apps/web/src/components/pure/help-island/style.ts
packages/component/src/ui/button/styles.ts

style: adjust icon button hover color

---

apps/electron/package.json
apps/electron/src/main/updater/index.ts
yarn.lock

may fix https://github.com/toeverything/AFFiNE/issues/2961

fix: potential updater issue

---

apps/electron/src/main/export/pdf.ts
packages/component/src/components/page-list/operation-menu-items/export.tsx
packages/i18n/src/resources/en.json
packages/i18n/src/resources/zh-Hans.json

fix: dark mode export PDF leaves margin and notification

---

apps/web/src/components/blocksuite/workspace-header/editor-mode-switch/index.tsx
apps/web/src/hooks/affine/use-shortcuts.ts

https://github.com/toeverything/AFFiNE/assets/12156547/cc5cea59-254f-4212-9092-9eae9b619840
Still WIP, but should able to cover most of the features in #2919

feat: page mode shortcut

---

apps/web/src/components/affine/create-workspace-modal/index.tsx
apps/web/src/components/affine/new-workspace-setting-detail/delete-leave-workspace/delete/index.tsx
apps/web/src/components/affine/new-workspace-setting-detail/profile.tsx
packages/component/src/components/page-list/view/create-collection.tsx
packages/component/src/ui/input/input.tsx
plugins/copilot/src/UI/debug-content.tsx

Docs: https://foxact.skk.moe/use-composition-input

refactor: input component

---

plugins/bookmark-block/project.json

Fixes: https://github.com/toeverything/AFFiNE/issues/3009

fix: bookmark block output missing

---

tests/parallels/local-first-collections-items.spec.ts

fix: flaky tests

---

apps/electron/package.json
apps/electron/src/main/updater/electron-updater.ts
yarn.lock

I spend a few hours debugging the issue and it looks like when using electron-updater v6 the updater instance will not capture some of the message.
may fix https://github.com/toeverything/AFFiNE/issues/2961

fix: updater issues

---

apps/web/src/components/affine/new-workspace-setting-detail/profile.tsx
apps/web/src/components/affine/setting-modal/setting-sidebar/index.tsx
tests/parallels/settings.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/3038

fix: workspace name should change in the setting panel

---

packages/component/src/components/page-list/view/collection-list.css.ts
tests/libs/filter.ts
tests/parallels/all-page.spec.ts
tests/parallels/local-first-collections-items.spec.ts

fix: date-picker hidden in update collection

---

apps/web/src/adapters/local/index.tsx
apps/web/src/atoms/index.ts
apps/web/src/components/affine/setting-modal/index.tsx
apps/web/src/components/pure/help-island/index.tsx
apps/web/src/layouts/workspace-layout.tsx
apps/web/src/providers/modal-provider.tsx

@QiShaoXuan Don't use `?` if you already know the default value. And set the workspace to null to avoid UI lagging

fix: cleanup workspace when switch setting panel

---

apps/web/src/atoms/root.ts
apps/web/src/components/affine/setting-modal/index.tsx
apps/web/src/components/affine/setting-modal/workspace-setting/index.tsx
apps/web/src/layouts/workspace-layout.tsx
packages/workspace/src/providers/index.ts

This is just a hot fix. Need sub doc connection reduce by @pengx17 and atom family in the future

perf: reduce unused provider connection

---

apps/web/src/components/cloud/login-card.tsx

Temporarily modify the style and wait for refactoring (https://github.com/toeverything/AFFiNE/issues/3067#issuecomment-1624838736)
Close #3067

style: temporarily modify user card

---

apps/electron/e2e/workspace.spec.ts
apps/electron/src/helper/db/base-db-adapter.ts
apps/electron/src/helper/db/workspace-db-adapter.ts

I suspect that there could be race condition that writes to workspace meta on initialization. So maybe adding a timeout could resolve the issur.

fix: a possible issue on electron flaky test

---

apps/web/src/atoms/settings.ts
apps/web/src/components/affine/setting-modal/general-setting/appearance/index.tsx
packages/component/package.json
packages/i18n/src/resources/en.json
yarn.lock

close https://github.com/toeverything/AFFiNE/issues/3057

feat: add font style setting 

---

packages/component/src/components/page-list/operation-menu-items/export.tsx
packages/component/src/components/share-menu/export.tsx
packages/component/src/components/share-menu/index.css.ts

chore: add new item for share component

---

apps/web/src/components/affine/affine-error-eoundary.tsx

Improve the error log so that we can easy to debug

feat: improve error log message

---

apps/web/src/components/blocksuite/workspace-header/editor-mode-switch/index.tsx
apps/web/src/components/blocksuite/workspace-header/editor-mode-switch/style.ts

style: change switch tip color

---

apps/server/src/modules/workspaces/resolver.ts
apps/server/src/schema.gql
apps/server/src/tests/utils.ts
apps/server/src/tests/workspace.spec.ts

add workspace.members[number].{permission, accepted}

feat: add member permission

---

apps/server/src/modules/auth/next-auth-options.ts
apps/server/src/modules/auth/next-auth.controller.ts
apps/web/src/hooks/affine/use-current-user.ts

Handle the `session.update` from `useSession` on the server side.

feat: implement updateSession in server side

---

apps/server/src/modules/auth/next-auth-options.ts
apps/server/src/modules/auth/next-auth.controller.ts

Currently the server's behavior was incorrect when logging in with an account password, this pr fixes it.

Fix password login user not exists

---

apps/web/src/atoms/settings.ts
apps/web/src/components/affine/setting-modal/general-setting/appearance/index.tsx
apps/web/src/components/affine/setting-modal/style.css.ts
apps/web/src/components/blocksuite/workspace-header/styles.css.ts
apps/web/src/layouts/workspace-layout.tsx
packages/component/package.json
packages/component/src/components/workspace/index.css.ts
packages/component/src/components/workspace/index.tsx
yarn.lock

fix: settings style update

---

apps/web/src/components/affine/setting-modal/workspace-setting/index.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/3164
Cherry Pick: https://github.com/toeverything/AFFiNE/commit/f12e2381133055130475b4bbb1f87a7d0c8960e5

fix: jump to index page after deletion

---

apps/server/src/modules/users/resolver.ts
apps/server/src/schema.gql
apps/server/src/tests/user.spec.ts
apps/server/src/tests/utils.ts
packages/graphql/src/graphql/delete-account.gql
packages/graphql/src/graphql/index.ts
packages/graphql/src/schema.ts

Should also handle workspaces and docs created by the user, I'll handle it in another pr.

feat: delete account

---

apps/web/next.config.mjs
apps/web/src/components/affine/setting-modal/general-setting/about/index.tsx
packages/env/src/global.ts
scripts/vitest/next-config-mock.ts

Related: https://github.com/toeverything/AFFiNE/issues/3168#issuecomment-1631062006

feat: display app version in setting panel

---

.github/workflows/workers.yml
packages/workers/src/index.ts

fix: enhancing the security of image proxy

---

apps/web/src/components/pure/workspace-slider-bar/collections/collections-list.tsx
apps/web/src/components/pure/workspace-slider-bar/collections/page.tsx
apps/web/src/components/pure/workspace-slider-bar/collections/styles.css.ts
packages/component/src/components/image-preview-modal/index.css.ts
packages/component/src/components/image-preview-modal/index.tsx
packages/component/src/components/page-list/operation-cell.tsx
packages/component/src/components/page-list/operation-menu-items/index.css.ts
packages/component/src/components/page-list/operation-menu-items/move-to-trash.tsx
packages/component/src/components/page-list/view/collection-bar.tsx
packages/component/src/components/page-list/view/collection-list.css.ts
packages/component/src/components/page-list/view/collection-list.tsx

style: update delete button style

---

packages/component/src/components/block-hub/index.tsx
tests/libs/editor.ts
tests/parallels/blocksuite/block-hub.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/3181

fix: block hub might not work

---

apps/web/src/components/blocksuite/block-suite-page-list/index.tsx
apps/web/src/components/pure/workspace-slider-bar/collections/collections-list.tsx
apps/web/src/components/workspace-header.tsx
apps/web/src/pages/workspace/[workspaceId]/[pageId].tsx
apps/web/src/pages/workspace/[workspaceId]/all.tsx
packages/component/src/components/page-list/__tests__/use-all-page-setting.spec.ts
packages/component/src/components/page-list/all-page.tsx
packages/component/src/components/page-list/type.ts
packages/component/src/components/page-list/use-collection-manager.ts
packages/component/src/components/page-list/view/collection-bar.tsx
packages/env/src/filter.ts

fix: collections should be unique for workspaces

---

apps/electron/scripts/macos-arm64-output-check.mts
apps/web/package.json
packages/plugin-infra/package.json
yarn.lock

Fixes: https://github.com/toeverything/AFFiNE/issues/3227

fix(plugin-infra): dependencies

---

apps/web/src/layouts/workspace-layout.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/3210

fix: remove hello-world page

---

apps/web/src/hooks/use-workspaces.ts
apps/web/src/layouts/workspace-layout.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/3256

fix: first workspace not found

---

packages/component/src/components/app-sidebar/app-updater-button/index.css.ts
packages/component/src/components/app-sidebar/app-updater-button/index.tsx

clicking quitAppAndInstall multiple times may cause some issues. This issue maybe related
https://github.com/electron/electron/issues/7792

fix: disable updater button when app updating

---

apps/web/src/components/affine/setting-modal/general-setting/about/index.tsx
packages/i18n/src/resources/en.json
packages/i18n/src/resources/zh-Hans.json

feat(i18n): support i18n in app version

---

packages/component/src/ui/scrollbar/index.css.ts

Close #3249 
https://github.com/toeverything/AFFiNE/assets/102217452/e35cfbcd-f106-426b-871e-88072649015e

fix: temporarily handle all page scroll bar styles

---

apps/storybook/src/stories/card.stories.tsx
apps/storybook/src/stories/import-page.stories.tsx
packages/component/src/components/card/block-card/index.tsx
packages/component/src/components/card/block-card/styles.css.ts
packages/component/src/components/import-page/index.css.ts
packages/component/src/components/import-page/index.tsx

Related to https://github.com/toeverything/blocksuite/issues/3316 https://github.com/toeverything/AFFiNE/pull/2533

feat: new import page component

---

packages/component/src/components/card/block-card/styles.css.ts
packages/component/src/components/import-page/index.css.ts
packages/component/src/components/page-list/components/new-page-buttton.tsx

chore: update block card styles

---

apps/core/src/components/blocksuite/workspace-header/header.tsx
apps/core/src/components/blocksuite/workspace-header/styles.css.ts

https://github.com/toeverything/AFFiNE/assets/102217452/49364067-e2b3-4130-aff1-93dd29dce50b

fix: banner blocking new page button issue

---

apps/web/src/components/blocksuite/workspace-header/download-tips.tsx
apps/web/src/components/blocksuite/workspace-header/header.tsx
packages/component/src/components/affine-banner/download-client.tsx
packages/i18n/src/resources/en.json
packages/i18n/src/resources/zh-Hans.json

https://github.com/toeverything/AFFiNE/assets/102217452/35a60599-ac56-41f9-a51d-e96692654487

chore: increase the frequency of the banner (#3264)

---

.github/helm/affine/templates/prometheus.yaml

ref: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/doc/api.md#clusterpodmonitoring

feat: use ClusterPodMonitoring

---

apps/core/.webpack/config.ts
apps/core/src/bootstrap/register-plugins.ts

code coverage will break the CSP
Related: https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/221

fix: lockdown

---

apps/core/src/components/affine/new-workspace-setting-detail/export.tsx

fix https://github.com/toeverything/AFFiNE/issues/3291

fix: temp workaround for missing blobs in export

---

packages/y-indexeddb/src/index.ts

Related: https://github.com/toeverything/AFFiNE/issues/3357

fix(y-indexeddb): un-track doc when destroy

---

packages/component/src/components/app-sidebar/menu-item/index.css.ts

chore: update icon size

---

packages/cli/src/bin/build-core.ts
packages/cli/src/bin/dev-core.ts
packages/cli/src/util/i18n.ts

Related: https://github.com/toeverything/AFFiNE/issues/3363

build: update cli

---

apps/electron/src/main/export/pdf.ts
packages/component/src/components/workspace/index.css.ts

close toeverything/blocksuite#3717 
close toeverything/AFFiNE#3387
close toeverything/AFFiNE#3388

fix: inconsistent database content in exported PDF

---

apps/core/src/components/pure/workspace-slider-bar/collections/collections-list.tsx
packages/component/src/components/app-sidebar/menu-item/index.css.ts

chore: adjust sidebar padding

---

apps/storybook/src/stories/notification-center.stories.tsx
packages/component/src/components/notification-center/index.css.ts
packages/component/src/components/notification-center/index.jotai.ts
packages/component/src/components/notification-center/index.tsx
packages/component/src/components/page-list/operation-menu-items/export.tsx

feat: support gif toast

---

apps/core/src/components/affine/setting-modal/setting-sidebar/index.tsx
apps/core/src/components/affine/setting-modal/setting-sidebar/style.css.ts
tests/affine-local/e2e/local-first-avatar.spec.ts

close: https://github.com/toeverything/AFFiNE/issues/3383

feat: modify current workspace label to a dot

---

packages/workspace/src/providers/sqlite-providers.ts

also need to cherry-pick to 0.7.0 staging branch

fix: sqlite db apply

---

apps/core/src/components/blocksuite/workspace-header/header-right-items/trash-button-group.tsx
apps/core/src/components/page-detail-editor.tsx
apps/core/src/hooks/use-navigate-helper.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/3412

fix(core): delete page

---

packages/component/src/components/page-list/filter/filter-list.tsx
packages/component/src/components/page-list/view/create-collection.tsx

https://github.com/toeverything/AFFiNE/assets/102217452/574705fd-a955-448f-8136-cfff33f15fa7

style: adjust collection modal style

---

apps/core/src/components/affine/new-workspace-setting-detail/delete-leave-workspace/delete/index.tsx
apps/core/src/components/affine/new-workspace-setting-detail/delete-leave-workspace/delete/style.ts

fix: bring back the lost WorkspaceDeleteModal style

---

apps/core/src/hooks/affine/use-block-suite-meta-helper.ts
packages/hooks/src/use-block-suite-page-meta.ts

Work for #2669 
Although I added this feature, but Blocksuite does not fully support read-only, we still need to wait for the upstream update.
Blocksuite issue url https://github.com/toeverything/blocksuite/issues/3750

feat: add read only mode for page in trash

---

apps/electron/e2e/workspace.spec.ts

test: add test for sub doc

---

.github/workflows/build.yml
apps/core/package.json
apps/core/src/bootstrap/register-plugins.ts
package.json
packages/cli/src/bin/dev-plugin.ts
plugins/copilot/package.json
plugins/copilot/src/UI/detail-content.tsx
plugins/copilot/src/UI/header-item.tsx
tests/affine-plugin/e2e/basic.spec.ts
tests/affine-plugin/package.json
tests/affine-plugin/playwright.config.ts
tests/affine-plugin/tsconfig.json
tsconfig.json
yarn.lock

Fixes: https://github.com/toeverything/AFFiNE/issues/3446

refactor: plugin loading logic

---

apps/core/src/components/affine/setting-modal/account-setting/index.tsx
apps/core/src/components/affine/setting-modal/setting-sidebar/index.tsx
apps/core/src/components/cloud/login-card.tsx
apps/core/src/components/pure/footer/index.tsx
apps/core/src/components/pure/footer/styles.ts

fixed: https://github.com/toeverything/AFFiNE/issues/3454

fix: error style

---

apps/core/server.mts
apps/core/src/atoms/index.ts
apps/core/src/pages/workspace/detail-page.tsx
apps/storybook/.storybook/main.ts
packages/component/src/components/notification-center/index.jotai.ts
packages/component/src/components/page-list/filter/logical/typesystem.ts
packages/component/src/ui/button/utils.ts
packages/hooks/src/use-block-suite-workspace-name.ts
packages/hooks/src/use-block-suite-workspace-page-is-public.ts
packages/plugin-infra/src/atom.ts
packages/workspace/src/manager/index.ts
packages/workspace/src/providers/__tests__/sqlite-provider.spec.ts
plugins/copilot/src/core/hooks/index.ts
tsconfig.json

Cherry Pick from https://github.com/toeverything/AFFiNE/pull/3475

chore: add `noUnusedLocals` and `noUnusedParameters` rules

---

apps/core/src/components/affine/setting-modal/general-setting/plugins/index.tsx
apps/core/src/components/affine/setting-modal/general-setting/plugins/style.css.ts
plugins/copilot/src/UI/debug-content.tsx

feat: add placeholder for OPENAI_API_KEY input

---

apps/core/package.json
apps/storybook/package.json
packages/component/package.json
packages/component/src/components/page-list/filter/shared-types.tsx
plugins/bookmark/package.json
plugins/hello-world/package.json
plugins/image-preview/package.json
yarn.lock

feat: brand new version of icons

---

apps/core/src/components/pure/workspace-list-modal/index.tsx
apps/core/src/components/pure/workspace-list-modal/styles.ts
packages/component/src/ui/scrollbar/scrollbar.tsx

modal button is sometimes not visible

fix: login modal style

---

apps/core/src/bootstrap/before-app.ts
apps/core/src/providers/modal-provider.tsx
packages/workspace/src/atom.ts

See https://blog.axlight.com/posts/how-to-use-jotai-and-use-transition-for-mutation/

fix: drag workspace

---

apps/core/src/components/blocksuite/block-suite-page-list/index.tsx
packages/i18n/src/resources/zh-Hans.json

caused by https://github.com/toeverything/AFFiNE/commit/20ee9d485dcbabe408350355e09bc36edda4f544#:~:text=(id%3F%3A%20string%2C%20mode%3F%3A%20%27page%27%20%7C%20%27edgeless%27)%20%3D%3E%20%7B
credits to @forehalo

fix: stackoverflow issue in empty page

---

docs/BUILDING.md

If you need to add more explanatory text, please request a change.

docs: update docs for build plugins

---

apps/core/src/components/blocksuite/workspace-header/editor-mode-switch/switch-items.tsx

https://github.com/toeverything/AFFiNE/assets/3471836/77d10598-e6f7-4c3b-b117-db83ef259a4d

fix: editor-mode-switch animation should only run once

---

apps/core/src/components/blocksuite/workspace-header/editor-mode-switch/style.ts

Fixes : #3532
added 4px padding and 8px gap.

fix: padding in the Switch button of Page/Edgeless

---

packages/component/src/theme/global.css

fix: scrollbar position offset

---

packages/y-indexeddb/src/provider.ts

related to https://github.com/toeverything/AFFiNE/issues/3494

fix: a possible double connect issue

---

apps/core/src/adapters/workspace.ts
apps/core/src/providers/modal-provider.tsx

looks like the root cause of https://github.com/toeverything/AFFiNE/pull/3507 is not fixed.

fix: test flaky

---

apps/core/src/components/blocksuite/workspace-header/header.tsx
apps/core/src/components/blocksuite/workspace-header/styles.css.ts
packages/component/src/components/page-list/all-page.tsx
packages/component/src/ui/button/styles.css.ts
plugins/copilot/src/UI/header-item.tsx

style: adjust page list header style

---

apps/core/src/components/affine/setting-modal/style.css.ts

fix: correct contact with us icon alignment

---

packages/component/src/components/page-list/view/collection-bar.css.ts
packages/component/src/components/page-list/view/collection-bar.tsx
packages/component/src/components/page-list/view/collection-list.tsx
packages/component/src/components/page-list/view/use-action.tsx

issue: https://github.com/toeverything/AFFiNE/issues/3498
It's just like CollectionBar
However, if a Tooltip is added, it will look strange.
I'm thinking maybe we can add a delay, for example, the Tooltip will disappear after one second.
Of course, I have temporarily removed the Tooltip now.

fix: collection-list pin icon not changed

---

apps/core/src/components/affine/setting-modal/setting-sidebar/index.tsx
apps/core/src/components/pure/footer/index.tsx
apps/core/src/components/pure/footer/styles.ts

fix: sign button all missing

---

apps/core/src/components/pure/help-island/index.tsx

https://github.com/toeverything/AFFiNE/assets/3471836/12c75c22-34d7-4d77-854d-564b2d7bb8e4
close #3638

fix: help island icons height

---

apps/core/src/router.ts

https://github.com/toeverything/AFFiNE/assets/3471836/16f9f708-589f-4e50-8c49-5f028fd8110b
ref: https://reactrouter.com/en/main/start/faq#how-do-i-add-a-no-match-404-route-in-react-router-v6
Maybe can handle #3641

feat: add no match route

---

tests/affine-local/e2e/all-page.spec.ts
tests/affine-local/e2e/local-first-collections-items.spec.ts
tests/kit/utils/filter.ts
tests/kit/utils/page-logic.ts

fix: test case

---

apps/core/src/bootstrap/plugins/setup.ts

fix: remove invisible unicode for dynamicImportKey

---

.eslintrc.js
apps/core/src/components/blocksuite/workspace-header/header-right-items/editor-option-menu.tsx
apps/electron/src/helper/db/__tests__/migration.spec.ts
apps/electron/src/helper/db/__tests__/workspace-db-adapter.spec.ts
apps/electron/src/helper/db/merge-update.ts
apps/electron/src/helper/db/migration.ts
apps/electron/src/helper/db/secondary-db.ts
apps/electron/src/helper/db/workspace-db-adapter.ts
packages/env/src/__tests__/subdoc-migration.spec.ts
packages/env/src/blocksuite/subdoc-migration.ts
packages/storage/__tests__/storage.spec.js
packages/y-indexeddb/src/__tests__/index.spec.ts
packages/y-indexeddb/src/provider.ts
packages/y-indexeddb/src/utils.ts

Upstream: https://github.com/yjs/yjs/issues/558

chore: prohibit using `mergeUpdates`

---

packages/hooks/src/use-block-suite-page-references.ts

fix https://github.com/toeverything/AFFiNE/issues/3660

fix: page references in list/database

---

packages/component/src/theme/global.css
tests/affine-local/e2e/open-affine.spec.ts

fix: get back the missing scrollbar

---

apps/electron/forge.config.js
apps/electron/scripts/generate-assets.mjs

fix https://github.com/toeverything/AFFiNE/issues/3666

fix: allow multiple versions to be installed on windows

---

packages/component/src/components/page-list/styles.ts

fixed: https://github.com/toeverything/AFFiNE/issues/3728

fix: error style of empty page

---

packages/infra/src/blocksuite/index.ts
packages/templates/v1/getting-started.json

Fixes: https://github.com/toeverything/AFFiNE/issues/3730

fix(core): first page

---

packages/templates/v1/getting-started.json

chore: adjust preloading page

---

apps/core/src/adapters/local/index.tsx
apps/core/src/hooks/use-workspaces.ts
packages/infra/src/blocksuite/index.ts
packages/templates/v1/getting-started.json

Fixes: https://github.com/toeverything/AFFiNE/issues/3731

fix(core): default page mode

---

apps/core/src/components/affine/setting-modal/style.css.ts

fix: add min height to footer

---

apps/electron/forge.config.js
apps/electron/scripts/dev.mjs

Some files need to be ignored in the final bundle.

fix: ignore some files to be bundled

---

apps/core/src/components/page-detail-editor.tsx
apps/electron/e2e/basic.spec.ts
packages/component/src/components/card/workspace-card/index.tsx

Also fix the test regression from https://github.com/toeverything/AFFiNE/pull/3700

fix(core): editor height incorrect

---

apps/core/src/components/pure/workspace-list-modal/index.tsx
apps/core/src/components/pure/workspace-list-modal/styles.ts
packages/component/src/components/card/workspace-card/index.tsx
packages/component/src/ui/tooltip/tooltip.tsx

Fixes overflow on electron and additional styling fixes.

fix: workspace dropdown fix

---

apps/electron/src/main/main-window.ts

workaround for https://github.com/electron/electron/issues/39576

fix: workaround for fullscreen mode

---

apps/core/src/bootstrap/plugins/setup.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/3840

fix(infra): dynamic import

---

apps/core/src/components/blocksuite/block-suite-page-list/utils.tsx

close https://github.com/toeverything/blocksuite/issues/4184

fix: jump to the correct url after importing notion

---

apps/core/src/components/pure/workspace-list-modal/index.tsx

Remove tooltip from workspace dropdown.

fix: remove tooltip

---

apps/server/src/modules/sync/events/events.gateway.ts
packages/workspace/src/affine/index.ts

Upstream: https://github.com/toeverything/AFFiNE/pull/3804

fix(server): trim guid on server side

---

tests/affine-local/e2e/quick-search.spec.ts

Please merge #3848 before merge this PR, or it will fail e2e

feat: e2e for recent search list

---

apps/core/src/components/pure/trash-button-group/index.tsx

fixed #3846
added toast messages

fix(core): add toast message

---

packages/component/src/components/workspace/index.css.ts

fix: make media print overflow visible

---

Cargo.lock

chore(storage): bump up upstream

---

apps/electron/scripts/generate-yml.js
apps/electron/scripts/make-squirrel.mts
apps/electron/src/main/updater/electron-updater.ts

1. support auto updater for windows (need to output a new latest.yml file and put into release)
2. fix installer icon

fix: support windows auto update

---

packages/component/src/components/page-list/view/create-collection.tsx
packages/component/src/ui/confirm/confirm.tsx

This commit will make #3838 more clear to review after rebasing this commit.

chore: modify code style

---

apps/storybook/src/stories/notification-center.stories.tsx
packages/component/src/components/notification-center/index.css.ts
packages/component/src/components/notification-center/index.tsx

https://github.com/toeverything/AFFiNE/assets/102217452/208100d6-502f-4fbb-9c5f-46301189ded0

refactor: add content to be selectable  and remove swipe gesture

---

apps/electron/package.json
apps/electron/scripts/generate-yml.js
yarn.lock

Upstream: https://github.com/toeverything/AFFiNE/pull/3911

fix: add missing package

---

apps/server/src/modules/doc/manager.ts
apps/server/src/modules/sync/events/events.gateway.ts
apps/server/src/modules/sync/events/workspace.ts
apps/server/src/modules/workspaces/controller.ts
apps/server/src/tests/doc.spec.ts
packages/workspace/src/affine/index.ts
packages/workspace/src/providers/sqlite-providers.ts
packages/y-indexeddb/src/provider.ts
packages/y-provider/src/__tests__/index.spec.ts
packages/y-provider/src/lazy-provider.ts
packages/y-provider/src/types.ts

```
client: doc-load ->                  -> send-update(diff)
server:          -> {missing, state}
```

fix(workspace): should load remote state in sync phase

---

apps/core/src/components/affine/setting-modal/setting-sidebar/index.tsx
apps/core/src/components/affine/setting-modal/setting-sidebar/style.css.ts

fix: error style of setting modal sidebar

---

packages/component/src/components/app-sidebar/sidebar-header/index.tsx

I swapped the positions of the forward and backward navigation bar and the receiving side sidebar buttons. #3636

fix: swap navigation bar items

---

apps/core/package.json
apps/server/package.json
apps/server/src/modules/workspaces/controller.ts
apps/server/src/modules/workspaces/permission.ts
apps/server/src/modules/workspaces/resolver.ts
packages/workspace/src/atom.ts
yarn.lock

Fixes: https://github.com/toeverything/AFFiNE/issues/3957

refactor(server): subpage logic

---

apps/electron/scripts/common.mjs

this allows debugger to step into source code directly

fix: enable electron sourcemap

---

apps/electron/src/helper/db/base-db-adapter.ts
packages/workspace/src/local/crud.ts

Hotpatch: https://github.com/toeverything/AFFiNE/issues/4034

fix(core): find lost data

---

apps/server/src/tests/prometheus-metrics.spec.ts

close https://github.com/toeverything/AFFiNE/issues/4024

fix: flaky unit test should be able to timer

---

.eslintrc.js
apps/core/src/components/affine/auth/after-sign-in-send-email.tsx
apps/core/src/components/affine/auth/after-sign-up-send-email.tsx
apps/core/src/components/affine/auth/index.tsx
apps/core/src/components/affine/auth/sign-in.tsx
apps/core/src/components/affine/setting-modal/account-setting/index.tsx
apps/core/src/components/cloud/login-card.tsx
apps/core/src/components/pure/footer/index.tsx
apps/core/src/utils/cloud-utils.tsx
packages/workspace/src/atom.ts

metadata might refresh after user login

fix(core): refresh metadata after refresh

---

apps/core/src/components/affine/setting-modal/account-setting/index.tsx
apps/server/src/modules/workspaces/resolver.ts
apps/server/src/schema.gql
packages/component/src/components/setting-components/index.tsx
packages/component/src/components/setting-components/share.css.ts
packages/component/src/components/setting-components/storage-progess.tsx
packages/graphql/src/graphql/blobs-size.gql
packages/graphql/src/graphql/index.ts
packages/graphql/src/schema.ts
packages/i18n/src/resources/en.json

feat: add storage panel in setting

---

apps/core/src/components/affine/setting-modal/general-setting/shortcuts/style.css.ts

fix: shortcut key style

---

apps/core/src/components/affine/new-workspace-setting-detail/index.tsx
apps/core/src/components/affine/new-workspace-setting-detail/labels.tsx
apps/core/src/components/affine/new-workspace-setting-detail/style.css.ts
apps/core/src/components/pure/header/style.css.tsx
apps/core/src/components/pure/workspace-list-modal/index.tsx
apps/core/src/components/pure/workspace-list-modal/styles.ts
apps/core/src/components/pure/workspace-slider-bar/WorkspaceSelector/styles.ts
apps/core/src/components/pure/workspace-slider-bar/WorkspaceSelector/workspace-selector.tsx
packages/component/src/components/app-sidebar/index.css.ts

feat: add worksapce type label

---

apps/core/src/components/pure/workspace-slider-bar/collections/add-collection-button.tsx
packages/component/src/components/page-list/view/create-collection.tsx
packages/i18n/src/resources/en.json
packages/i18n/src/resources/fr.json
packages/i18n/src/resources/zh-Hant.json

fix: corrected the preposition in "Save As New Collection"

---

apps/core/.webpack/config.ts
apps/electron/scripts/generate-assets.mjs
apps/electron/src/main/protocol.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/4021

fix: add back sourcemaps to electron build

---

apps/core/package.json
plugins/copilot/package.json
plugins/hello-world/package.json
plugins/image-preview/package.json
plugins/outline/package.json
yarn.lock

fix: error in @toeverything/components

---

apps/server/src/modules/auth/mailer/mail.service.ts

Fixed invitation url jump to 0.0.0.0

fix: error invitation url

---

packages/component/src/components/page-list/use-sorter.ts

- Sort tags by count on all page
- Supports custom sorting fn in useSorter
Before 
https://github.com/toeverything/AFFiNE/assets/18554747/753e352d-4b97-43e8-bf69-4380ec3906e7

fix(core): sort tags by count

---

apps/core/src/components/affine/auth/after-sign-in-send-email.tsx
apps/core/src/components/affine/auth/after-sign-up-send-email.tsx
apps/core/src/components/affine/auth/sign-in.tsx
apps/core/src/components/affine/auth/use-auth.ts

feat: optimize sign in experience

---

packages/component/src/components/page-list/filter/vars.tsx

fix: filter of tags does not work

---

apps/core/src/components/blocksuite/block-suite-page-list/utils.tsx
apps/core/src/components/pure/workspace-slider-bar/favorite/add-favourite-button.tsx
apps/core/src/components/root-app-sidebar/index.tsx
tests/affine-local/e2e/local-first-favorites-items.spec.ts

feat: add fav button

---

packages/workspace/src/local/crud.ts

fix https://github.com/toeverything/AFFiNE/issues/4195

fix: cloud workspace sometimes converted to local workspace

---

apps/server/src/modules/auth/next-auth-options.ts
apps/server/src/modules/auth/resolver.ts
apps/server/src/modules/auth/service.ts

use session cookie from database to sign user in electron

fix: use database session cookie for production

---

apps/core/src/components/affine/new-workspace-setting-detail/style.css.ts

fix: https://github.com/toeverything/AFFiNE/issues/4175

fix: can not scroll in mermber list

---

apps/core/src/pages/sign-in.tsx

- Close https://github.com/toeverything/AFFiNE/issues/4177

fix(core): location.state maybe null

---

packages/i18n/src/resources/en.json

close: https://github.com/toeverything/AFFiNE/issues/4136

feat: modify workspace setting description

---

apps/server/src/modules/auth/next-auth.controller.ts

- Close https://github.com/toeverything/AFFiNE/issues/4218

chore(server): redirect /api/auth/signin

---

apps/core/src/components/migration-fallback.tsx
tests/affine-cloud/e2e/basic.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/4240

fix(core): upload binary after migration

---

packages/i18n/src/resources/en.json

fix: correct sign out display name

---

apps/core/src/components/affine/auth/send-email.tsx
packages/i18n/src/resources/en.json

fixed: https://github.com/toeverything/AFFiNE/issues/4230

fix: wrong copywriting in change email modal

---

apps/core/src/components/share-page-not-found-error.tsx
apps/core/src/pages/share/detail-page.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/4224

feat(core): add share page error boundary

---

packages/component/src/components/card/workspace-card/styles.ts

https://github.com/toeverything/AFFiNE/assets/102217452/8f9f6099-20db-4ef2-b635-0422a9d34689

style: add hover style to the setting button in workspace card

---

apps/electron/src/main/updater/electron-updater.ts

fix https://github.com/toeverything/AFFiNE/issues/4246

fix: disable simutanous updater download

---

apps/core/src/providers/modal-provider.tsx
packages/component/src/components/workspace-list/index.tsx

https://github.com/toeverything/AFFiNE/assets/584378/2a9d848e-1801-462a-bb81-3adda86b3498

fix: better transition

---

apps/server/src/modules/auth/mailer/mail.service.ts

fixed: https://github.com/toeverything/AFFiNE/issues/4213
fixed: https://github.com/toeverything/AFFiNE/issues/4212

fix: wrong content in invitation email

---

apps/server/src/modules/auth/mailer/mail.service.ts
apps/server/src/modules/auth/mailer/template.ts

fixed: https://github.com/toeverything/AFFiNE/issues/4264

fix: incorrect invitation email style

---

apps/server/migrations/20230906100042_user_feature_gates/migration.sql
apps/server/schema.prisma
apps/server/src/config/def.ts
apps/server/src/config/default.ts
apps/server/src/modules/auth/next-auth-options.ts
apps/server/src/modules/auth/next-auth.controller.ts
apps/server/src/modules/auth/utils/index.ts
apps/server/src/modules/auth/utils/jwt.ts
apps/server/src/modules/auth/utils/send-mail.ts
apps/server/src/modules/users/gates.ts
apps/server/src/modules/users/index.ts
apps/server/src/modules/users/resolver.ts
apps/server/src/modules/users/users.ts
apps/server/src/modules/workspaces/index.ts
apps/server/src/modules/workspaces/permission.ts
apps/server/src/modules/workspaces/resolver.ts
apps/server/src/schema.gql
apps/server/src/tests/auth.spec.ts
apps/server/src/tests/utils.ts
apps/server/src/tests/workspace-blobs.spec.ts
apps/server/src/throttler.ts
packages/graphql/src/fetcher.ts
packages/graphql/src/graphql/blob-check-size.gql
packages/graphql/src/graphql/index.ts
packages/graphql/src/schema.ts
packages/workspace/src/blob/cloud-blob-storage.ts

feat: server refactor

---

packages/i18n/src/resources/en.json

fixed: https://github.com/toeverything/AFFiNE/issues/4252

fix: modify back text

---

apps/server/src/middleware/exception-logger.ts
apps/server/src/modules/auth/next-auth.controller.ts
apps/server/src/modules/doc/manager.ts
apps/server/src/modules/doc/redis-manager.ts
apps/server/src/modules/workspaces/controller.ts

merge logs in logging system like this:

feat: keep the multiline log in single log

---

tests/affine-plugin/e2e/basic.spec.ts

fix flaky plugin test
eg. https://github.com/toeverything/AFFiNE/actions/runs/6120132171/job/16611380535

fix: sort plugin list in test

---

apps/core/package.json
apps/core/src/components/affine/language-menu/index.tsx
apps/core/src/components/blocksuite/block-suite-header-title/operation-menu.tsx
apps/core/src/components/pure/workspace-list-modal/index.tsx
apps/core/src/components/pure/workspace-list-modal/styles.ts
packages/component/src/components/card/workspace-card/styles.ts
packages/component/src/components/page-list/filter/index.css.ts
packages/component/src/components/page-list/filter/vars.tsx
packages/component/src/components/page-list/operation-cell.tsx
packages/component/src/components/page-list/operation-menu-items/export.tsx
packages/component/src/components/page-list/operation-menu-items/index.css.ts
packages/component/src/components/page-list/view/collection-list.css.ts
packages/component/src/components/page-list/view/collection-list.tsx
packages/component/src/components/share-menu/index.css.ts
packages/component/src/components/share-menu/share-export.tsx
packages/component/src/components/share-menu/share-menu.tsx
packages/component/src/components/share-menu/share-page.tsx
plugins/copilot/package.json
plugins/hello-world/package.json
plugins/image-preview/package.json
plugins/outline/package.json
yarn.lock

fix: menu style

---

packages/component/src/theme/global.css

possibly fix https://github.com/toeverything/AFFiNE/issues/4296

fix: potential issue that may push whole window up a bit

---

apps/core/src/providers/session-provider.tsx

fix: unexpected react warning

---

apps/core/src/pages/desktop-signin.tsx
apps/core/src/pages/open-app.tsx
apps/core/src/utils/cloud-utils.tsx
apps/electron/src/main/deep-link.ts

fix https://github.com/toeverything/AFFiNE/issues/4319

fix: signout account when logging through oauth signin via desktop

---

apps/core/src/components/affine/new-workspace-setting-detail/export.tsx
packages/i18n/src/resources/en.json

1. force syncing idb to sqlite when exporting
2. toast -> notification

fix: force syncing DB when export db

---

packages/component/src/components/share-menu/share-menu.tsx

fix: wrong share status display

---

apps/core/src/components/page-detail-editor.css.ts
apps/core/src/components/page-detail-editor.tsx

close: https://github.com/toeverything/blocksuite/issues/4728

feat: hide page info in public pages

---

apps/core/src/components/pure/quick-search-modal/index.tsx

fix: error style of quick search modal

---

.eslintrc.js
apps/core/src/components/affine/auth/send-email.tsx
apps/core/src/components/pure/header/index.tsx
apps/core/src/components/pure/header/top-tip.tsx
apps/core/src/components/pure/header/windows-app-controls.tsx
apps/core/src/components/root-app-sidebar/index.tsx
apps/core/src/providers/session-provider.tsx
apps/core/src/utils/cloud-utils.tsx
apps/storybook/.storybook/preview.tsx
packages/component/src/components/page-list/operation-cell.tsx
packages/component/src/components/theme-provider/index.tsx
packages/workspace/src/manager/index.ts

fix: add platform selector to storybook

---

apps/core/src/hooks/use-location-title.ts
apps/core/src/utils/user-setting.ts
tests/affine-local/e2e/local-first-collections-items.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/4376

fix(core): local workspace collections

---

apps/core/src/components/affine/setting-modal/setting-sidebar/style.css.ts

fix: error style of setting sidebar

---

apps/core/src/pages/404.tsx
packages/component/src/components/not-found-page/index.tsx
packages/component/src/components/not-found-page/not-found-page.tsx
packages/component/src/components/not-found-page/not-found-pattern.tsx
packages/component/src/components/not-found-page/styles.css.ts
packages/i18n/src/resources/en.json

close: https://github.com/toeverything/AFFiNE/issues/4339
close: https://github.com/toeverything/AFFiNE/issues/4320

feat: modify 404 page

---

packages/component/src/components/not-found-page/not-found-page.tsx
tests/affine-local/e2e/exception-page.spec.ts
tests/affine-local/e2e/local-first-avatar.spec.ts
tests/affine-local/e2e/quick-search.spec.ts
tests/affine-local/e2e/router.spec.ts

caused by @QiShaoXuan in https://github.com/toeverything/AFFiNE/commit/26877ffd5264088458d66ca4c387edfa88461766

test: fix e2e

---

apps/server/src/modules/workspaces/permission.ts
apps/server/tests/workspace.e2e.ts

fix: read permission for subpage

---

packages/graphql/src/fetcher.ts
packages/workspace/src/providers/cloud/index.ts

close https://github.com/toeverything/AFFiNE/issues/4394

feat: apply higher priority for doc request

---

apps/storybook/project.json

Add more production files as inputs of storybook:
1. apps/core/src
2. production files of deps

ci(storybook): add production file of deps to be inputs of storybook

---

packages/component/src/components/app-sidebar/sidebar-header/index.tsx

chore: add back&forward for web​

---

apps/core/src/components/page-detail-editor.css.ts
apps/core/src/components/page-detail-editor.tsx
apps/storybook/src/stories/core.stories.tsx
packages/component/src/components/workspace/index.css.ts

close #4278 
close #4345
Some related PR https://github.com/toeverything/AFFiNE/pull/3800 cc @JimmFly

fix(core): editor popover covered header popover

---

apps/electron/src/main/protocol.ts

fix: allow file protocol streaming

---

apps/core/src/components/affine/setting-modal/workspace-setting/index.tsx
packages/infra/src/__internal__/workspace.ts

close #4428
Not sure if this is an appropriate fix, feel free to modify it.

fix: providers get disconnected after opening the setting and close it

---

packages/infra/src/__internal__/workspace.ts
packages/infra/src/__tests__/workspace.spec.ts

Upstream: https://github.com/toeverything/AFFiNE/pull/4429

test: workspace passive provider

---

apps/core/package.json
plugins/copilot/package.json
plugins/hello-world/package.json
plugins/image-preview/package.json
plugins/outline/package.json
yarn.lock

chore: bump components version

---

apps/server/src/app.ts
apps/server/tests/sync.spec.ts

sync server is unable to bootstrap on cluster because of the missing dependency.

fix(server): missing dependency in sync app

---

apps/core/src/components/affine/auth/sign-in.tsx
apps/server/src/modules/users/resolver.ts

fix(core): error state for non early access user while signing in with email

---

apps/server/migrations/20230922071241_payment/migration.sql
apps/server/schema.prisma
apps/server/src/config/def.ts
apps/server/src/config/default.ts
apps/server/src/config/index.ts
apps/server/src/index.ts
apps/server/src/modules/payment/index.ts
apps/server/src/modules/payment/resolver.ts
apps/server/src/modules/payment/service.ts
apps/server/src/modules/payment/webhook.ts
apps/server/src/schema.gql

feat(server): user subscription checkout

---

packages/component/src/components/app-sidebar/menu-item/index.css.ts

Close #4426 
https://github.com/toeverything/AFFiNE/assets/102217452/5d38642b-52fb-4d0d-8e40-7da48e3ba393

fix: unexpected hover behavior of collection sidebar

---

apps/core/src/components/affine/setting-modal/setting-sidebar/index.tsx
apps/core/src/components/affine/setting-modal/setting-sidebar/style.css.ts
apps/core/src/components/pure/cmdk/data.tsx
apps/core/src/components/pure/cmdk/main.css.ts
apps/core/src/components/pure/cmdk/main.tsx

- fix https://github.com/toeverything/AFFiNE/issues/4487
- fix cmdk item padding (right scrollbar placeholder)
- fix scroll to the first item issue when query changed
- add padding for the first command item in cmdk

fix: cmdk scrollbar gutter

---

packages/component/src/components/workspace/index.css.ts

Remove background color animation of app to avoid different experience when change color scheme.
https://github.com/toeverything/AFFiNE/assets/9527419/6a2dce55-ea52-41b1-92b8-47f3382797b7

fix(component): background animation is different

---

packages/component/src/components/share-menu/share-page.tsx

fix: unexpected pop ups

---

packages/component/src/components/not-found-page/not-found-page.tsx
packages/component/src/components/not-found-page/styles.css.ts

fix: adjust 404 page style

---

apps/core/src/components/page-detail-editor.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/4494

fix(core): page update date

---

apps/storybook/src/stories/core.stories.tsx

fix https://github.com/toeverything/AFFiNE/issues/4464

fix: storybook previews

---

packages/sdk/src/entry.ts
plugins/outline/src/app.tsx

Fixes: https://github.com/toeverything/AFFiNE/issues/4505

fix: current page atom

---

apps/core/src/components/blocksuite/block-suite-page-list/utils.tsx
apps/core/src/components/pure/cmdk/data.tsx
apps/core/src/components/pure/workspace-slider-bar/favorite/add-favourite-button.tsx
apps/storybook/src/stories/quick-search/quick-search-main.stories.tsx

fix https://github.com/toeverything/AFFiNE/issues/4510

fix(component): cmdk flaky

---

packages/component/src/components/share-menu/index.css.ts
packages/component/src/components/share-menu/share-export.tsx
packages/component/src/components/share-menu/share-menu.tsx
packages/component/src/components/share-menu/share-page.tsx
packages/component/src/components/share-menu/use-share-url.ts

feat(component): add private copy link button

---

apps/core/src/components/affine/setting-modal/index.tsx
apps/core/src/components/affine/setting-modal/style.css.ts

fix(core): setting ui regression

---

apps/electron/src/main/ui/handlers.ts

Examples:
https://twitter.com/xjasonlyu/status/1707751239448973418
https://x.com/FarSideOfMoonvy/status/1676046421894791168
https://x.com/ElaineYan_/status/1707990761156084111
https://x.com/himseIf_65/status/1702038497966834071
---
P.S.
Notion is using `https://cdn.syndication.twimg.com/tweet-result` but I didn't find out what is this

fix: twitter preview

---

apps/electron/scripts/macos-arm64-output-check.mts

Regression by: https://github.com/toeverything/AFFiNE/pull/4544

fix(electron): output check

---

apps/core/src/components/affine/share-page-modal/index.tsx
apps/core/src/components/workspace-header.tsx
packages/component/src/components/share-menu/index.css.ts
packages/component/src/components/share-menu/share-export.tsx
packages/component/src/components/share-menu/share-menu.tsx
packages/component/src/components/share-menu/share-page.tsx
packages/i18n/src/resources/en.json
tests/affine-cloud/e2e/collaboration.spec.ts
tests/kit/utils/cloud.ts

Close #4528 
https://github.com/toeverything/AFFiNE/assets/102217452/e496060a-700a-4fc7-a38f-b6237675d0ec

feat(core): adjust share menu style

---

apps/server/migrations/20231013011816_payment/migration.sql
apps/server/schema.prisma
apps/server/src/config/def.ts
apps/server/src/config/index.ts
apps/server/src/modules/payment/resolver.ts
apps/server/src/modules/payment/service.ts
apps/server/src/modules/payment/webhook.ts
apps/server/src/schema.gql
packages/graphql/src/schema.ts

```
query {
prices {
// ...
}
}
`

feat(server): dynamic fetching prices

---

tests/affine-local/e2e/router.spec.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/4589

test(core): fix flaky

---

apps/core/src/atoms/index.ts
apps/core/src/components/affine/setting-modal/account-setting/index.tsx
apps/core/src/components/affine/sign-out-modal/index.tsx
apps/core/src/components/pure/workspace-slider-bar/user-with-workspace-list/user-account/index.tsx
apps/core/src/pages/404.tsx
apps/core/src/providers/modal-provider.tsx
packages/component/src/components/share-menu/share-menu.tsx
packages/i18n/src/resources/en.json
tests/affine-cloud/e2e/collaboration.spec.ts
tests/affine-desktop/e2e/basic.spec.ts
tests/affine-desktop/e2e/workspace.spec.ts
tests/affine-local/e2e/router.spec.ts
tests/kit/utils/cloud.ts

Close #4580 
https://github.com/toeverything/AFFiNE/assets/102217452/6f526678-bf2c-4d32-8253-8646b05e7a91

feat(core): add sign out confirm modal

---

apps/core/src/components/root-app-sidebar/index.tsx
apps/core/src/hooks/affine/use-shortcuts.ts
apps/core/src/hooks/use-shortcut-commands.ts
packages/component/src/components/app-sidebar/index.tsx
packages/component/src/components/app-sidebar/sidebar-header/index.tsx
tests/affine-desktop/e2e/basic.spec.ts

feat(core): add history shortcut

---

packages/y-indexeddb/package.json
packages/y-indexeddb/vite.config.ts

Fixes: https://github.com/toeverything/AFFiNE/issues/4624

build(y-indexeddb): fix output package.json

---

apps/server/src/modules/doc/manager.ts
apps/server/src/modules/doc/redis-manager.ts
apps/server/src/modules/sync/events/events.gateway.ts
apps/server/src/modules/workspaces/controller.ts
apps/server/src/modules/workspaces/permission.ts
apps/server/src/modules/workspaces/resolver.ts
apps/server/src/utils/__tests__/doc.spec.ts
apps/server/src/utils/doc.ts
apps/server/tests/doc.spec.ts
packages/graphql/src/graphql/index.ts
packages/graphql/src/graphql/set-revoke-page.gql
packages/graphql/src/graphql/set-share-page.gql
packages/graphql/src/schema.ts

close #4132
walkaround for #4338

fix: make server guid consistent

---

packages/frontend/core/src/components/affine/enable-affine-cloud-modal/index.tsx

fix: wrong confirm button position

---

.github/workflows/deploy.yml
packages/backend/server/schema.prisma
packages/backend/server/src/storage/index.ts

- Close https://github.com/toeverything/AFFiNE/issues/4549

build: fix native module in aarch64 docker image

---

packages/frontend/core/src/components/affine/setting-modal/general-setting/billing/index.tsx
packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/index.tsx
packages/frontend/core/src/hooks/use-subscription.ts

```
const [subscription, updateSubscription] = useUserSubscription()
// will update the cache and revalidate
updateSubscription({ canceledAt: now() })
```

refactor(core): make subscription hook

---

Cargo.lock

- Fix https://github.com/toeverything/AFFiNE/security/dependabot/45

fix(storage): rustix security fix

---

packages/frontend/core/src/components/pure/cmdk/main.css.ts
packages/frontend/core/src/components/pure/cmdk/main.tsx
tests/storybook/src/stories/quick-search/quick-search-modal.stories.tsx

fix(component): disable CMDK list animation

---

packages/frontend/core/src/components/affine/auth/style.css.ts
packages/frontend/core/src/components/affine/auth/user-plan-button.tsx
packages/frontend/core/src/components/affine/setting-modal/setting-sidebar/index.tsx
packages/frontend/core/src/components/affine/setting-modal/setting-sidebar/style.css.ts
packages/frontend/core/src/components/pure/workspace-slider-bar/user-with-workspace-list/user-account/index.css.ts
packages/frontend/core/src/components/pure/workspace-slider-bar/user-with-workspace-list/user-account/index.tsx

https://github.com/toeverything/AFFiNE/assets/102217452/f19f50ce-46ef-4849-8ebd-544153734d30

feat(core): add account subscription status

---

packages/common/env/src/global.ts
packages/frontend/core/.webpack/runtime-config.ts
packages/frontend/core/package.json
packages/frontend/core/src/atoms/index.ts
packages/frontend/core/src/components/affine/payment-disable/index.tsx
packages/frontend/core/src/components/affine/payment-disable/style.css.ts
packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/plan-card.tsx
packages/frontend/core/src/providers/modal-provider.tsx
packages/frontend/i18n/src/resources/en.json
packages/plugins/copilot/package.json
packages/plugins/hello-world/package.json
packages/plugins/image-preview/package.json
packages/plugins/outline/package.json
yarn.lock

Run `ENABLE_PAYMENT=false yarn dev` to develop in local

feat(core): disable payment in canary

---

packages/frontend/workspace/src/affine/index.ts

Before fix:
https://github.com/toeverything/AFFiNE/assets/50035259/f762d5ef-00bb-45fe-855f-5349c3e670fa

fix: remove awareness state before window unload

---

.github/helm/affine/charts/graphql/templates/migration.yaml
packages/backend/server/migrations/20231027090128_data_migration/migration.sql
packages/backend/server/package.json
packages/backend/server/schema.prisma
packages/backend/server/src/data/app.ts
packages/backend/server/src/data/commands/create.ts
packages/backend/server/src/data/commands/run.ts
packages/backend/server/src/data/migrations/1698398506533-guid.ts
packages/backend/server/src/middleware/exception-logger.ts
packages/backend/server/src/modules/doc/manager.ts
yarn.lock

feat(server): add data migration system

---

packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/plan-card.tsx

fix: request prevented when re-downgrade subscribe

---

packages/frontend/core/src/components/affine/auth/after-sign-in-send-email.tsx
packages/frontend/core/src/components/affine/auth/subscription-redirect.css.ts
packages/frontend/core/src/components/affine/auth/subscription-redirect.tsx
packages/frontend/core/src/components/affine/auth/use-auth.ts
packages/frontend/core/src/components/affine/auth/use-subscription.ts
packages/frontend/core/src/pages/auth.tsx
packages/frontend/i18n/src/resources/en.json

Use `${baseUrl}/signin?subscription_recurring=Yearly&subscription_plan=Pro` to login and subscribe plan

feat(core): support subscribe plan after login

---

packages/frontend/component/src/components/page-list/filter/condition.tsx
packages/frontend/component/src/components/page-list/filter/index.css.ts
packages/frontend/component/src/components/page-list/filter/multi-select.css.ts
packages/frontend/component/src/components/page-list/view/edit-collection.tsx

1. text color of search input
2. style for the multi-select tag
3. date-picker autofocus issue

fix(core): text color of search input, style for the multi-select tag, date-picker autofocus issue

---

docs/BUILDING.md

docs: change yarn version in BUILDING.md

---

packages/frontend/core/src/pages/workspace/page-list-empty.tsx
packages/frontend/i18n/src/resources/en.json

chore(i18n): add new key for empty trash page

---

packages/common/infra/package.json
packages/frontend/core/src/components/pure/workspace-slider-bar/favorite/favorite-list.tsx
packages/frontend/core/src/layouts/workspace-layout.tsx
packages/frontend/hooks/package.json
packages/frontend/hooks/src/use-block-suite-workspace-page.ts
packages/frontend/hooks/tsconfig.json
yarn.lock

1. use `p-queue` to throttle load events
2. load all pages after 10s
workaround for https://github.com/toeverything/AFFiNE/issues/4825

perf(core): load all pages after 10s

---

packages/frontend/core/src/hooks/use-register-workspace-commands.ts
packages/frontend/core/src/pages/workspace/detail-page.tsx

fix(core): duplicate registration in edgeless

---

packages/common/infra/vite.config.ts
packages/frontend/component/src/components/notification-center/index.jotai.ts
packages/frontend/component/src/components/notification-center/index.tsx
packages/frontend/component/src/components/page-list/operation-menu-items/export.tsx
packages/frontend/component/src/components/provider-composer/__tests__/provider-composer.spec.tsx
packages/frontend/component/src/components/share-menu/share-page.tsx
packages/frontend/component/src/components/workspace-list/index.tsx
packages/frontend/component/src/ui/popper/popper.tsx
packages/frontend/component/src/ui/tree-view/tree-node-inner.tsx
packages/frontend/core/src/adapters/cloud/ui.tsx
packages/frontend/core/src/adapters/local/index.tsx
packages/frontend/core/src/adapters/public-cloud/ui.tsx
packages/frontend/core/src/components/affine/auth/use-captcha.tsx
packages/frontend/core/src/components/affine/auth/user-plan-button.tsx
packages/frontend/core/src/components/affine/new-workspace-setting-detail/export.tsx
packages/frontend/core/src/components/affine/setting-modal/account-setting/index.tsx
packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/index.tsx
packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/plan-card.tsx
packages/frontend/core/src/components/blocksuite/block-suite-header-title/operation-menu.tsx
packages/frontend/core/src/components/cloud/provider.tsx
packages/frontend/core/src/components/page-detail-editor.tsx
packages/frontend/core/src/components/pure/footer/index.tsx
packages/frontend/core/src/components/root-app-sidebar/index.tsx
packages/frontend/core/src/layouts/workspace-layout.tsx
packages/frontend/core/src/pages/workspace/all-page.tsx
packages/frontend/core/src/pages/workspace/trash-page.tsx
tests/storybook/src/stories/app-sidebar.stories.tsx
tests/storybook/src/stories/quick-search/quick-search-modal.stories.tsx

Fix some code style issues from [`oxlint`](https://github.com/web-infra-dev/oxc), mainly useless `React.Fragment`

chore: fix code style issues

---

packages/frontend/core/src/components/affine/auth/subscription-redirect.css.ts
packages/frontend/core/src/components/affine/auth/subscription-redirect.tsx
packages/frontend/core/src/pages/sign-in.tsx
packages/frontend/i18n/src/resources/en.json

1. redirect to the payment URL when the user has logged in
2. show the subscription existing page when the user has subscribed

fix(core): visit /signin pay when already logged and subscribed

---

packages/backend/server/src/modules/auth/resolver.ts

fix(server): token set with id instead of email

---

packages/frontend/component/src/components/page-list/components/floating-toobar.tsx
packages/frontend/component/src/components/page-list/page-group.tsx
packages/frontend/component/src/components/page-list/page-header.tsx
packages/frontend/core/src/pages/workspace/all-page.tsx
tests/affine-local/e2e/all-page.spec.ts

- select all in page list group header does not need to enable selection
- also added some tests to all pages

fix(core): select all in page list group header does not need to enable selection

---

.github/actions/build-rust/action.yml
.github/actions/setup-node/action.yml
.github/workflows/build-desktop.yml
.github/workflows/release-desktop-app.yml
yarn.lock

It works https://github.com/toeverything/AFFiNE/actions/runs/6808724617/job/18513791415

ci: disable postinstall on macOS build

---

.github/actions/deploy/deploy.mjs
.github/helm/affine/charts/graphql/templates/deployment.yaml
.github/helm/affine/charts/graphql/values.yaml
packages/backend/server/src/config/default.ts

- Scale the pod counts to 10
- Set `earlyAccessPreview` to false

ci: adjust the beta cluster configuration

---

packages/common/debug/src/index.ts
packages/frontend/core/src/app.tsx
packages/frontend/core/src/bootstrap/setup.ts
packages/frontend/core/src/index.tsx
packages/frontend/core/src/pages/workspace/all-page.tsx
packages/frontend/core/src/pages/workspace/detail-page.tsx
packages/frontend/core/src/pages/workspace/index.tsx
packages/frontend/core/src/shared/index.ts
packages/frontend/workspace/src/affine/sync.ts
packages/frontend/workspace/src/atom.ts

Add more performance log to debug loading problem

chore: add performance logger

---

Cargo.lock
packages/backend/storage/Cargo.toml
packages/frontend/native/Cargo.toml

brings https://github.com/toeverything/OctoBase/pull/558

chore(server): bump octobase versions

---

.github/workflows/build.yml
packages/backend/server/src/modules/sync/events/events.gateway.ts

- https://github.com/toeverything/AFFiNE/pull/4908
- https://github.com/toeverything/AFFiNE/pull/4913

fix: cherry pick hotfix back to master

---

packages/frontend/component/src/components/page-list/page-tags.css.ts
packages/frontend/component/src/components/page-list/page-tags.tsx
tests/storybook/src/stories/page-list.stories.tsx

fix(storybook): page tags display

---

packages/frontend/core/src/pages/workspace/index.tsx

https://github.com/toeverything/AFFiNE/pull/4912 this only works for local data, but not for cloud workspace

fix(core): change server url of stable to insider (#4902)

---

.github/workflows/nightly-build.yml

Should be part of https://github.com/toeverything/AFFiNE/pull/4885

ci: disable postinstall in nightly desktop build

---

packages/backend/server/src/modules/workspaces/resolver.ts

fix(server): all viewers can share public link

---

.devcontainer/Dockerfile
.devcontainer/build.sh
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/setup-user.sh
README.md
build.sh

This pr add a devcontainer.json config, modify from figadore's old pr https://github.com/toeverything/AFFiNE/pull/4725
* PostgreSQL database ready
* Preinstall graphite, auto auth of you have codespace secrets config

chore: add devcontainer config

---

packages/frontend/component/src/components/notification-center/index.css.ts

closed #4705 
https://github.com/toeverything/AFFiNE/assets/39363750/f6038135-ed43-4591-ab01-1ee66c652bb3

fix(component): stack notification cards expand animation

---

packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/layout.css.ts
packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/plan-card.tsx
packages/frontend/core/src/components/affine/setting-modal/general-setting/plans/style.css.ts

closes #4889 
- **Before**
- **After**

style(core): update pro plan card style

---

packages/frontend/component/src/ui/toast/toast.ts

close #4835 
https://github.com/toeverything/AFFiNE/assets/102217452/feb1af6e-c269-4041-904f-f3e221563152

feat(core): keep the latest toast showing when multiple call
